# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for DashForge single-binary distribution."""

import os
from pathlib import Path

block_cipher = None
root = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    [os.path.join(root, "dashforge", "cli.py")],
    pathex=[root],
    binaries=[],
    datas=[
        (os.path.join(root, "archetypes.yaml"), "."),
        (os.path.join(root, "dashforge", "static"), "dashforge/static"),
    ],
    hiddenimports=[
        "dashforge.main",
        "dashforge.cli",
        "dashforge.config",
        "dashforge.pipeline",
        "dashforge.feedback",
        "dashforge.ranking",
        "dashforge.cache",
        "dashforge.validation",
        "dashforge.agents",
        "dashforge.agents.intent",
        "dashforge.agents.providers",
        "dashforge.agents.providers.registry",
        "dashforge.agents.providers.anthropic",
        "dashforge.agents.providers.openai_provider",
        "dashforge.agents.providers.ollama",
        "dashforge.archetypes",
        "dashforge.archetypes.engine",
        "dashforge.archetypes.templates",
        "dashforge.grafana",
        "dashforge.grafana.client",
        "dashforge.grafana.adapters",
        "dashforge.grafana.adapters.prometheus",
        "dashforge.grafana.adapters.cloudwatch",
        "dashforge.grafana.adapters.influxdb",
        "dashforge.grafana.adapters.graphite",
        "dashforge.grafana.adapters.signalfx",
        "dashforge.signalfx",
        "dashforge.signalfx.client",
        "dashforge.signalfx.discovery",
        "dashforge.signalfx.publisher",
        "dashforge.history",
        "dashforge.context",
        "dashforge.integrations",
        "dashforge.models",
        "dashforge.models.schemas",
        "uvicorn",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "click",
        "rich",
        "yaml",
        "httpx",
        "pydantic",
        "pydantic_settings",
        "structlog",
        "fastapi",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="dashforge",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
