"""Tacit CLI — single-command local startup for on-call engineers."""

from __future__ import annotations

import json
import os
import webbrowser
from collections.abc import Callable
from concurrent.futures import Future
from pathlib import Path
from typing import Any

import click
import yaml

# ── Constants ────────────────────────────────────────────────────────────────
TACIT_HOME = Path.home() / ".tacit"
CONFIG_FILE = TACIT_HOME / "config.yaml"


def _get_version() -> str:
    """Derive version from package metadata to avoid drift with pyproject.toml."""
    # 1. Try installed package metadata (works after pip install -e .)
    try:
        from importlib.metadata import version

        for distribution in ("tacit-ai", "tacit"):
            try:
                return version(distribution)
            except Exception:
                pass
    except Exception:
        pass
    # 2. Fallback: parse pyproject.toml directly (running from source)
    try:
        import re

        toml_path = Path(__file__).resolve().parent.parent / "pyproject.toml"
        if toml_path.exists():
            match = re.search(r'^version\s*=\s*"([^"]+)"', toml_path.read_text(), re.MULTILINE)
            if match:
                return match.group(1)
    except Exception:
        pass
    return "0.0.0-dev"


VERSION = _get_version()

# ── Rich helpers (graceful fallback) ─────────────────────────────────────────
console: Any
Prompt: Any | None
Confirm: Any | None
Table: Any | None

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Confirm as RichConfirm
    from rich.prompt import Prompt as RichPrompt
    from rich.table import Table as RichTable

    console = Console()
    Prompt = RichPrompt
    Confirm = RichConfirm
    Table = RichTable

    def _success(msg: str) -> None:
        console.print(f"  [bold green]✔[/] {msg}")

    def _warn(msg: str) -> None:
        console.print(f"  [bold yellow]⚠[/] {msg}")

    def _fail(msg: str) -> None:
        console.print(f"  [bold red]✘[/] {msg}")

    def _info(msg: str) -> None:
        console.print(f"  [dim]→[/] {msg}")

    def _header(msg: str) -> None:
        console.print(Panel(f"[bold]{msg}[/]", border_style="blue"))

except ImportError:
    # Fallback: plain text
    class _FakeConsole:
        def print(self, msg: str = "", **kw: Any) -> None:
            click.echo(msg)

    console = _FakeConsole()

    def _success(msg: str) -> None:
        click.echo(f"  ✔ {msg}")

    def _warn(msg: str) -> None:
        click.echo(f"  ⚠ {msg}")

    def _fail(msg: str) -> None:
        click.echo(f"  ✘ {msg}")

    def _info(msg: str) -> None:
        click.echo(f"  → {msg}")

    def _header(msg: str) -> None:
        click.echo(f"\n{'─' * 60}\n  {msg}\n{'─' * 60}")

    Prompt = None
    Confirm = None
    Table = None


def _prompt(text: str, default: str = "") -> str:
    """Interactive prompt with Rich fallback."""
    if Prompt is not None:
        return Prompt.ask(f"  {text}", default=default or None) or default
    return click.prompt(f"  {text}", default=default)


def _confirm(text: str, default: bool = True) -> bool:
    if Confirm is not None:
        return Confirm.ask(f"  {text}", default=default)
    return click.confirm(f"  {text}", default=default)


# ── CLI Group ────────────────────────────────────────────────────────────────
@click.group()
@click.version_option(VERSION, prog_name="tacit")
def cli():
    """Tacit — Natural language → Grafana dashboards."""
    pass


# ── tacit init ───────────────────────────────────────────────────────────
@cli.command()
@click.option("--non-interactive", is_flag=True, help="Skip prompts, use defaults")
def init(non_interactive: bool):
    """Interactive setup wizard. Creates ~/.tacit/config.yaml."""
    _header("Tacit Setup")

    if CONFIG_FILE.exists() and not non_interactive:
        if not _confirm("Config already exists. Overwrite?", default=False):
            _info("Keeping existing config.")
            return

    TACIT_HOME.mkdir(parents=True, exist_ok=True)

    if non_interactive:
        config = _default_config()
        _info("Using default config (non-interactive mode)")
    else:
        config = _interactive_setup()

    # Write config (secrets go to .env, not YAML)
    config_data, secrets = _split_config(config)
    with open(CONFIG_FILE, "w") as f:
        f.write("# Tacit configuration — generated by `tacit init`\n")
        f.write("# Secrets (API keys) are in ~/.tacit/.env\n\n")
        yaml.dump(config_data, f, default_flow_style=False, sort_keys=False)

    env_path = TACIT_HOME / ".env"
    with open(env_path, "w") as f:
        f.write("# Tacit secrets — generated by `tacit init`\n")
        for k, v in secrets.items():
            f.write(f"{k}={v}\n")
    env_path.chmod(0o600)

    _success(f"Config written to {CONFIG_FILE}")
    _success(f"Secrets written to {env_path}")
    console.print()
    _info("Next steps:")
    _info("  tacit doctor   — validate your setup")
    _info("  tacit test     — run a sample investigation")
    _info("  tacit serve    — start the API server")


def _default_config() -> dict:
    return {
        "grafana_url": "http://localhost:3000",
        "grafana_api_key": "",
        "grafana_org_id": 1,
        "llm_provider": "anthropic",
        "llm_api_key": "",
        "llm_model": "claude-sonnet-4-20250514",
        "llm_api_base": "",
        "log_level": "INFO",
    }


def _interactive_setup() -> dict:
    config: dict = {}
    console.print()

    # ── Grafana ──
    _header("Grafana Connection")
    config["grafana_url"] = _prompt("Grafana URL", "http://localhost:3000")
    config["grafana_api_key"] = _prompt("Grafana API key (service account token)", "")
    config["grafana_org_id"] = int(_prompt("Grafana Org ID", "1"))

    # ── LLM ──
    console.print()
    _header("LLM Provider")
    config["llm_provider"] = _prompt("Provider (anthropic/openai/azure/bedrock/ollama)", "anthropic")

    if config["llm_provider"] != "bedrock":
        config["llm_api_key"] = _prompt("LLM API key", "")
    else:
        config["llm_api_key"] = ""  # Bedrock uses IAM, not API keys

    model_defaults = {
        "anthropic": "claude-sonnet-4-20250514",
        "openai": "gpt-4o",
        "azure": "gpt-4o",
        "bedrock": "anthropic.claude-sonnet-4-20250514-v1:0",
        "ollama": "llama3",
    }
    default_model = model_defaults.get(config["llm_provider"], "claude-sonnet-4-20250514")
    config["llm_model"] = _prompt("Model name", default_model)

    if config["llm_provider"] in ("azure", "ollama"):
        config["llm_api_base"] = _prompt("API base URL", "")
    elif config["llm_provider"] == "bedrock":
        config["llm_api_base"] = ""
        config["llm_bedrock_region"] = _prompt("AWS region", "us-east-1")
        config["llm_bedrock_role_arn"] = _prompt("IAM role ARN to assume (leave empty for default chain)", "")
        if _confirm("Use explicit AWS access keys? (No = use IAM role/instance profile)", default=False):
            config["llm_aws_access_key_id"] = _prompt("AWS Access Key ID", "")
            config["llm_aws_secret_access_key"] = _prompt("AWS Secret Access Key", "")
    else:
        config["llm_api_base"] = ""

    # ── Slack (optional) ──
    console.print()
    if _confirm("Configure Slack integration?", default=False):
        _header("Slack Integration")
        config["slack_bot_token"] = _prompt("Bot token (xoxb-...)", "")
        config["slack_app_token"] = _prompt("App token (xapp-...)", "")
        config["slack_signing_secret"] = _prompt("Signing secret", "")

    # ── Splunk SignalFx (optional) ──
    console.print()
    if _confirm("Configure Splunk SignalFx (Observability Cloud) integration?", default=False):
        _header("Splunk SignalFx")
        config["signalfx_enabled"] = True
        config["signalfx_api_token"] = _prompt("API token (SFx access token)", "")
        config["signalfx_realm"] = _prompt("Realm (us0, us1, us2, eu0, jp0, au0)", "us1")
        config["signalfx_dashboard_group"] = _prompt("Dashboard group name", "Tacit")
    else:
        config["signalfx_enabled"] = False

    config["log_level"] = "INFO"
    return config


def _split_config(config: dict) -> tuple[dict, dict]:
    """Split config into YAML-safe settings and secrets (.env)."""
    secret_keys = {
        "grafana_api_key": "GRAFANA_API_KEY",
        "llm_api_key": "LLM_API_KEY",
        "slack_bot_token": "SLACK_BOT_TOKEN",
        "slack_app_token": "SLACK_APP_TOKEN",
        "slack_signing_secret": "SLACK_SIGNING_SECRET",
        "signalfx_api_token": "SIGNALFX_API_TOKEN",
        "llm_aws_access_key_id": "LLM_AWS_ACCESS_KEY_ID",
        "llm_aws_secret_access_key": "LLM_AWS_SECRET_ACCESS_KEY",
    }
    yaml_config: dict = {}
    secrets: dict = {}

    for k, v in config.items():
        if k in secret_keys:
            if v:
                secrets[secret_keys[k]] = v
        else:
            yaml_config[k] = v

    # Map non-secret config keys to env-style for the yaml
    structured: dict = {
        "grafana": {
            "url": yaml_config.pop("grafana_url", "http://localhost:3000"),
            "org_id": yaml_config.pop("grafana_org_id", 1),
        },
        "llm": {
            "provider": yaml_config.pop("llm_provider", "anthropic"),
            "model": yaml_config.pop("llm_model", "claude-sonnet-4-20250514"),
        },
    }
    api_base = yaml_config.pop("llm_api_base", "")
    if api_base:
        structured["llm"]["api_base"] = api_base

    # Bedrock config
    bedrock_region = yaml_config.pop("llm_bedrock_region", "")
    bedrock_role_arn = yaml_config.pop("llm_bedrock_role_arn", "")
    if structured["llm"].get("provider") == "bedrock" or bedrock_region:
        if bedrock_region:
            structured["llm"]["bedrock_region"] = bedrock_region
        if bedrock_role_arn:
            structured["llm"]["bedrock_role_arn"] = bedrock_role_arn

    # SignalFx config
    sfx_enabled = yaml_config.pop("signalfx_enabled", False)
    sfx_realm = yaml_config.pop("signalfx_realm", "")
    sfx_group = yaml_config.pop("signalfx_dashboard_group", "")
    if sfx_enabled or sfx_realm:
        structured["signalfx"] = {
            "enabled": sfx_enabled,
        }
        if sfx_realm:
            structured["signalfx"]["realm"] = sfx_realm
        if sfx_group:
            structured["signalfx"]["dashboard_group"] = sfx_group

    structured["log_level"] = yaml_config.pop("log_level", "INFO")

    # Carry over any remaining keys
    structured.update(yaml_config)
    return structured, secrets


# ── tacit doctor ─────────────────────────────────────────────────────────
@cli.command()
def doctor():
    """Validate Grafana, datasources, LLM connectivity, and cache state."""
    _header("Tacit Doctor")
    _load_env()

    from concurrent.futures import ThreadPoolExecutor, as_completed

    # ── Synchronous local checks (instant) ────────────────────────────
    checks_passed = 0
    checks_total = 0
    fatal_failures: list[str] = []
    warnings: list[str] = []

    # 1. Config file
    checks_total += 1
    if CONFIG_FILE.exists():
        _success(f"Config found: {CONFIG_FILE}")
        checks_passed += 1
    else:
        _warn(f"No config at {CONFIG_FILE} — run `tacit init`")
        fatal_failures.append("config")

    # 2. Archetypes (local file check, no network)
    checks_total += 1
    arch_ok = _check_archetypes()
    if arch_ok:
        checks_passed += 1
    else:
        warnings.append("archetypes")

    # 3. Cache dir
    checks_total += 1
    data_dir = Path("data")
    if data_dir.exists():
        _success(f"Data directory exists: {data_dir.resolve()}")
        checks_passed += 1
    else:
        _info("Data directory will be created on first run")
        checks_passed += 1  # Not a failure

    # ── Parallel network checks ───────────────────────────────────────
    # Run Grafana, LLM, and SignalFx checks concurrently to reduce wall time
    sfx_enabled = False
    try:
        from tacit.config import settings as _sfx_settings

        sfx_enabled = _sfx_settings.signalfx_enabled and bool(_sfx_settings.signalfx_api_token)
    except Exception:
        pass

    network_checks: dict[str, Callable[[], bool]] = {
        "grafana": _check_grafana,
        "llm": _check_llm,
    }
    if sfx_enabled:
        network_checks["signalfx"] = _check_signalfx

    network_results: dict[str, bool] = {}
    with ThreadPoolExecutor(max_workers=len(network_checks)) as pool:
        futures: dict[Future[bool], str] = {pool.submit(fn): name for name, fn in network_checks.items()}
        for future in as_completed(futures):
            name = futures[future]
            try:
                network_results[name] = future.result()
            except Exception:
                network_results[name] = False

    grafana_ok = network_results.get("grafana", False)

    # Zero-key mode downgrades a missing LLM key from fatal to warning:
    # deterministic intent + the archetype engine still produce dashboards.
    llm_zero_key = _llm_zero_key_mode()

    checks_total += len(network_checks)
    for name, ok in network_results.items():
        if ok:
            checks_passed += 1
        elif name == "llm" and llm_zero_key:
            warnings.append("llm (zero-key mode)")
        else:
            fatal_failures.append(name)

    # 4. Datasource discovery (depends on Grafana — sequential)
    ds_ok = False
    if grafana_ok:
        checks_total += 1
        ds_ok = _check_datasources()
        if ds_ok:
            checks_passed += 1
        else:
            warnings.append("datasources")

    # 5. Operational knowledge inventory (local stores — instant)
    knowledge = {"dashboards": 0, "alerts": 0, "runbooks": 0, "incidents": 0}
    readiness_level = ""
    try:
        from tacit.assess import build_assessment

        _report = build_assessment()
        _inv = _report["inventory"]
        knowledge = {
            "dashboards": _inv["dashboards_ingested"],
            "alerts": _inv["alerts_ingested"],
            "runbooks": _inv["runbooks"],
            "incidents": _inv["incidents"],
        }
        readiness_level = _report["readiness"]["level"]
    except Exception:
        _warn("Knowledge inventory unavailable (stores not initialized yet)")

    # ── Readiness checklist ───────────────────────────────────────────
    console.print()
    _header("Readiness")

    def _check_row(label: str, ok: bool, detail: str, fix: str = "") -> None:
        if ok:
            _success(f"{label:<14} {detail}")
        else:
            _fail(f"{label:<14} {detail}" + (f" — {fix}" if fix else ""))

    _check_row("Grafana", grafana_ok, "connected" if grafana_ok else "not connected", "tacit connect grafana")
    if grafana_ok:
        _check_row("Datasources", ds_ok, "discovered" if ds_ok else "none found", "check Grafana datasources")
    llm_ok = network_results.get("llm", False)
    if llm_ok:
        _check_row("LLM", True, "configured")
    elif llm_zero_key:
        _warn(f"{'LLM':<14} zero-key mode (deterministic fallback active)")
    else:
        _check_row("LLM", False, "not configured", "set LLM_API_KEY in ~/.tacit/.env")
    if sfx_enabled:
        _check_row("SignalFx", network_results.get("signalfx", False), "connected", "tacit connect signalfx")
    _check_row(
        "Dashboards",
        knowledge["dashboards"] > 0,
        f"{knowledge['dashboards']} learned" if knowledge["dashboards"] else "none learned",
        "tacit learn grafana",
    )
    _check_row(
        "Alerts",
        knowledge["alerts"] > 0,
        f"{knowledge['alerts']} learned" if knowledge["alerts"] else "none learned",
        "tacit learn alerts",
    )
    _check_row(
        "Runbooks",
        knowledge["runbooks"] > 0,
        f"{knowledge['runbooks']} learned" if knowledge["runbooks"] else "none learned",
        "tacit learn runbooks --dir <path>",
    )
    _check_row(
        "Incidents",
        knowledge["incidents"] > 0,
        f"{knowledge['incidents']} learned" if knowledge["incidents"] else "none learned",
        "tacit learn incidents / tacit learn pagerduty",
    )

    console.print()
    ready = not fatal_failures
    if ready:
        verdict = "Ready" + (f" — investigation readiness: {readiness_level}" if readiness_level else "")
        _success(f"Assessment: {verdict}")
        _info("Deep-dive with: tacit assess")
    else:
        _fail(f"Assessment: Not ready ({checks_passed}/{checks_total} checks passed)")
        _fail(f"Fatal: {', '.join(fatal_failures)}")
        if "grafana" in fatal_failures:
            _info("Run `tacit connect grafana` to fix Grafana connection")
        if "signalfx" in fatal_failures:
            _info("Run `tacit connect signalfx` to fix SignalFx connection")
        if "llm" in fatal_failures:
            _info("Check your LLM_API_KEY in ~/.tacit/.env")
    if warnings:
        _warn(f"Warnings: {', '.join(warnings)}")


def _load_env():
    """Load ~/.tacit/.env and point config to ~/.tacit/config.yaml."""
    env_file = TACIT_HOME / ".env"
    if env_file.exists():
        from dotenv import load_dotenv

        load_dotenv(env_file)

    if CONFIG_FILE.exists() and not os.environ.get("TACIT_CONFIG"):
        os.environ["TACIT_CONFIG"] = str(CONFIG_FILE)


def _llm_zero_key_mode() -> bool:
    """True only when deterministic fallback applies to a key-based provider."""
    try:
        from tacit.agents.intent_fallback import zero_key_mode
        from tacit.config import settings

        return settings.intent_fallback_enabled and zero_key_mode(settings)
    except Exception:
        return False


def _check_grafana() -> bool:
    try:
        import httpx

        from tacit.config import settings

        url = settings.grafana_url.rstrip("/")
        api_key = settings.grafana_api_key

        if not api_key:
            _warn("Grafana: no API key configured")
            return False

        headers = {"Authorization": f"Bearer {api_key}"}
        resp = httpx.get(f"{url}/api/org", headers=headers, timeout=10)
        if resp.status_code == 200:
            org = resp.json()
            _success(f"Grafana: connected to \"{org.get('name', 'unknown')}\" at {url}")
            return True
        else:
            _fail(f"Grafana: HTTP {resp.status_code} from {url}/api/org")
            return False
    except Exception as e:
        _fail(f"Grafana: {e}")
        return False


def _check_datasources() -> bool:
    try:
        import httpx

        from tacit.config import settings

        url = settings.grafana_url.rstrip("/")
        headers = {"Authorization": f"Bearer {settings.grafana_api_key}"}
        resp = httpx.get(f"{url}/api/datasources", headers=headers, timeout=10)
        if resp.status_code == 200:
            ds_list = resp.json()
            types: dict[str, int] = {}
            for ds in ds_list:
                t = ds.get("type", "unknown")
                types[t] = types.get(t, 0) + 1
            summary = ", ".join(f"{v}× {k}" for k, v in sorted(types.items()))
            _success(f"Datasources: {len(ds_list)} found ({summary})")
            return True
        else:
            _fail(f"Datasources: HTTP {resp.status_code}")
            return False
    except Exception as e:
        _fail(f"Datasources: {e}")
        return False


def _check_llm() -> bool:
    try:
        from tacit.config import settings

        provider = settings.llm_provider.lower()
        api_key = settings.llm_api_key
        model = settings.llm_model
        api_base = settings.llm_api_base

        if provider == "openai" and api_base:
            _success(f"LLM: {provider} / {model} at {api_base} (OpenAI-compatible endpoint configured)")
            return True

        if not api_key and provider not in ("ollama", "bedrock"):
            if settings.intent_fallback_enabled:
                _warn(
                    f"LLM: no API key for {provider} — zero-key mode active "
                    "(deterministic intent + archetype engine only)"
                )
            else:
                _warn(f"LLM: no API key for {provider}")
            return False

        # Light validation — don't actually call the API
        if provider == "anthropic" and api_key.startswith("sk-ant-"):
            _success(f"LLM: {provider} / {model} (key looks valid)")
            return True
        elif provider in ("openai", "azure") and api_key.startswith("sk-"):
            _success(f"LLM: {provider} / {model} (key looks valid)")
            return True
        elif provider == "bedrock":
            try:
                import boto3

                session_kwargs: dict = {"region_name": settings.llm_bedrock_region}
                if settings.llm_aws_access_key_id:
                    session_kwargs["aws_access_key_id"] = settings.llm_aws_access_key_id
                    session_kwargs["aws_secret_access_key"] = settings.llm_aws_secret_access_key
                session = boto3.Session(**session_kwargs)
                # Mirror _build_boto3_session: assume role if configured
                if settings.llm_bedrock_role_arn:
                    sts = session.client("sts")
                    assumed = sts.assume_role(
                        RoleArn=settings.llm_bedrock_role_arn,
                        RoleSessionName="tacit-bedrock",
                        DurationSeconds=3600,
                    )
                    creds = assumed["Credentials"]
                    session = boto3.Session(
                        aws_access_key_id=creds["AccessKeyId"],
                        aws_secret_access_key=creds["SecretAccessKey"],
                        aws_session_token=creds["SessionToken"],
                        region_name=settings.llm_bedrock_region,
                    )
                sts = session.client("sts")
                identity = sts.get_caller_identity()
                account = identity.get("Account", "?")
                model_id = settings.llm_bedrock_model_id or model
                _success(f"LLM: bedrock / {model_id} (AWS account {account}, region {settings.llm_bedrock_region})")
                return True
            except ImportError:
                _fail("LLM: bedrock requires boto3 — uv sync --extra bedrock (or pip install 'tacit[bedrock]')")
                return False
            except Exception as be:
                _fail(f"LLM: bedrock AWS auth failed — {be}")
                return False
        elif provider == "ollama":
            import httpx

            base = settings.llm_api_base or "http://localhost:11434"
            try:
                resp = httpx.get(f"{base}/api/tags", timeout=5)
                if resp.status_code == 200:
                    _success(f"LLM: ollama at {base} / {model}")
                    return True
            except Exception:
                pass
            _warn(f"LLM: ollama at {base} not reachable")
            return False
        else:
            _success(f"LLM: {provider} / {model} (key present)")
            return True
    except Exception as e:
        _fail(f"LLM: {e}")
        return False


def _check_archetypes() -> bool:
    try:
        from tacit.archetypes.templates import ALL_ARCHETYPES

        total_panels = sum(len(a.panels) for a in ALL_ARCHETYPES)
        _success(f"Archetypes: {len(ALL_ARCHETYPES)} loaded, {total_panels} panels")
        return True
    except Exception as e:
        _fail(f"Archetypes: {e}")
        return False


def _check_signalfx() -> bool:
    try:
        import httpx

        from tacit.config import settings

        realm = settings.signalfx_realm
        token = settings.signalfx_api_token
        if not token:
            _warn("SignalFx: no API token configured")
            return False

        resp = httpx.get(
            f"https://api.{realm}.signalfx.com/v2/metric",
            headers={"X-SF-TOKEN": token},
            params={"query": "*", "limit": 1},
            timeout=10,
        )
        if resp.status_code == 200:
            data = resp.json()
            count = data.get("count", "?")
            _success(f"SignalFx: connected to realm {realm} ({count} metrics)")
            return True
        elif resp.status_code == 401:
            _fail("SignalFx: authentication failed (HTTP 401) — check API token")
            return False
        else:
            _fail(f"SignalFx: HTTP {resp.status_code} from api.{realm}.signalfx.com")
            return False
    except Exception as e:
        _fail(f"SignalFx: {e}")
        return False


# ── tacit connect grafana ────────────────────────────────────────────────
@cli.group()
def connect():
    """Connect to external services."""
    pass


@connect.command("grafana")
@click.option("--url", default=None, help="Grafana URL")
@click.option("--api-key", default=None, help="Grafana service account token")
def connect_grafana(url: str | None, api_key: str | None):
    """Test and persist Grafana connection."""
    _header("Connect to Grafana")
    _load_env()

    if url is None:
        url = _prompt("Grafana URL", "http://localhost:3000")
    if api_key is None:
        api_key = _prompt("API key (service account token)", "")

    if not api_key:
        _fail("API key is required")
        return

    # Test connection
    import httpx

    try:
        headers = {"Authorization": f"Bearer {api_key}"}
        resp = httpx.get(f"{url.rstrip('/')}/api/org", headers=headers, timeout=10)
        if resp.status_code != 200:
            _fail(f"Connection failed: HTTP {resp.status_code}")
            return
        org = resp.json()
        _success(f"Connected to \"{org.get('name', 'unknown')}\" at {url}")
    except Exception as e:
        _fail(f"Connection failed: {e}")
        return

    # Discover datasources
    try:
        resp = httpx.get(f"{url.rstrip('/')}/api/datasources", headers=headers, timeout=10)
        if resp.status_code == 200:
            ds_list = resp.json()
            _success(f"Found {len(ds_list)} datasources:")
            for ds in ds_list:
                _info(f"  {ds['name']} ({ds['type']})")
    except Exception:
        pass

    # Persist
    if _confirm("Save this connection?", default=True):
        _ensure_config()
        _update_config({"grafana": {"url": url}})
        _update_env({"GRAFANA_API_KEY": api_key})
        _success("Connection saved!")
        _info("Run `tacit doctor` to verify full setup")


@connect.command("signalfx")
@click.option("--token", default=None, help="SignalFx API access token")
@click.option("--realm", default=None, help="SignalFx realm (us0, us1, us2, eu0, jp0, au0)")
def connect_signalfx(token: str | None, realm: str | None):
    """Test and persist Splunk SignalFx connection."""
    _header("Connect to Splunk SignalFx")
    _load_env()

    if realm is None:
        realm = _prompt("Realm (us0, us1, us2, eu0, jp0, au0)", "us1")
    if token is None:
        token = _prompt("API access token", "")

    if not token:
        _fail("API token is required")
        return

    # Test connection
    import httpx

    try:
        resp = httpx.get(
            f"https://api.{realm}.signalfx.com/v2/metric",
            headers={"X-SF-TOKEN": token},
            params={"query": "*", "limit": 1},
            timeout=10,
        )
        if resp.status_code == 401:
            _fail("Authentication failed — check your API token")
            return
        if resp.status_code != 200:
            _fail(f"Connection failed: HTTP {resp.status_code}")
            return
        data = resp.json()
        count = data.get("count", "?")
        _success(f"Connected to realm {realm} ({count} metrics available)")
    except Exception as e:
        _fail(f"Connection failed: {e}")
        return

    group_name = _prompt("Dashboard group name", "Tacit")

    # Persist
    if _confirm("Save this connection?", default=True):
        _ensure_config()
        _update_config({"signalfx": {"enabled": True, "realm": realm, "dashboard_group": group_name}})
        _update_env({"SIGNALFX_API_TOKEN": token})
        _success("Connection saved!")
        _info("Run `tacit doctor` to verify full setup")


def _ensure_config():
    TACIT_HOME.mkdir(parents=True, exist_ok=True)
    if not CONFIG_FILE.exists():
        CONFIG_FILE.write_text("# Tacit configuration\n")


def _update_config(updates: dict):
    """Merge updates into the YAML config file."""
    existing: dict = {}
    if CONFIG_FILE.exists():
        with open(CONFIG_FILE) as f:
            existing = yaml.safe_load(f) or {}

    def _deep_merge(base: dict, override: dict) -> dict:
        for k, v in override.items():
            if isinstance(v, dict) and isinstance(base.get(k), dict):
                base[k] = _deep_merge(base[k], v)
            else:
                base[k] = v
        return base

    merged = _deep_merge(existing, updates)
    with open(CONFIG_FILE, "w") as f:
        yaml.dump(merged, f, default_flow_style=False, sort_keys=False)


def _update_env(updates: dict):
    """Merge key=value pairs into ~/.tacit/.env."""
    env_path = TACIT_HOME / ".env"
    existing: dict = {}
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                existing[k.strip()] = v.strip()
    existing.update(updates)
    with open(env_path, "w") as f:
        f.write("# Tacit secrets\n")
        for k, v in existing.items():
            f.write(f"{k}={v}\n")
    env_path.chmod(0o600)


# ── tacit test ───────────────────────────────────────────────────────────
@cli.command("investigate")
@click.argument("prompt", required=False)
@click.option("--json", "json_output", is_flag=True, help="Print the canonical Investigation Contract JSON")
@click.option("--open-browser/--no-open-browser", default=False, help="Open dashboard rendering in browser")
def investigate(prompt: str | None, json_output: bool, open_browser: bool):
    """Run an investigation and render the versioned contract."""
    _load_env()
    if prompt is None:
        prompt = "High latency on the checkout service in the last hour"

    import asyncio

    async def _run():
        from tacit.history import get_investigation_store
        from tacit.models.schemas import DashRequest
        from tacit.pipeline import run_pipeline

        result = await run_pipeline(DashRequest(prompt=prompt, user_id="cli"))
        contract = None
        if result.investigation_id:
            contract = get_investigation_store().get_contract(result.investigation_id, result.investigation_revision)
        return result, contract

    try:
        result, contract = asyncio.run(_run())
    except Exception as e:
        _fail(f"Investigation error: {e}")
        _info("Run `tacit doctor` to check your setup")
        raise SystemExit(1) from e

    if json_output:
        if contract is None:
            _fail("Investigation completed without a persisted contract")
            raise SystemExit(1)
        click.echo(json.dumps(contract.model_dump(mode="json", by_alias=True), indent=2, sort_keys=True))
        return

    _header("Investigation Complete")
    if result.dashboard_url:
        _success(f"Dashboard rendering: {result.dashboard_url}")
    else:
        _warn("No dashboard rendering URL returned")
    if result.investigation_id and result.investigation_revision is not None:
        _info(f"Investigation: {result.investigation_id} revision {result.investigation_revision}")
    _info(f"Panels: {result.panel_count}")
    if contract is not None:
        _info(f"Grounding: {contract.grounding.status.value}")
        _info(f"Conclusion: {contract.grounding.maximum_trustworthy_conclusion.get('text', '')}")
    if open_browser and result.dashboard_url:
        webbrowser.open(result.dashboard_url)


@cli.command("test")
@click.option("--prompt", "-p", default=None, help="Custom test prompt")
@click.option("--open-browser/--no-open-browser", default=True, help="Open dashboard in browser")
def test_run(prompt: str | None, open_browser: bool):
    """Run a sample investigation and open the resulting dashboard."""
    _header("Tacit Test Run")
    _load_env()

    if prompt is None:
        prompt = "High latency on the checkout service in the last hour"
    _info(f'Prompt: "{prompt}"')
    console.print()

    import asyncio

    async def _run():
        from tacit.models.schemas import DashRequest
        from tacit.pipeline import run_pipeline

        req = DashRequest(prompt=prompt)
        _info("Running pipeline...")
        result = await run_pipeline(req)
        return result

    try:
        result = asyncio.run(_run())

        if result.dashboard_url:
            _success(f"Dashboard created: {result.dashboard_url}")
            _info(f"  UID: {result.dashboard_uid}")
            _info(f"  Panels: {result.panel_count}")
            _info(f"  Path: {result.path_used}")
            if result.archetypes:
                arch_str = ", ".join(f"{a.type} ({a.confidence:.0%})" for a in result.archetypes)
                _info(f"  Archetypes: {arch_str}")

            if open_browser and result.dashboard_url:
                _info("Opening in browser...")
                webbrowser.open(result.dashboard_url)
        else:
            _fail("Pipeline completed but no dashboard URL returned")
            if result.error:
                _fail(f"Error: {result.error}")

    except Exception as e:
        _fail(f"Pipeline error: {e}")
        _info("Run `tacit doctor` to check your setup")


# ── tacit demo ───────────────────────────────────────────────────────────
@cli.command()
@click.option("--down", "tear_down", is_flag=True, help="Tear down the demo stack and exit")
@click.option("--no-build", is_flag=True, help="Skip docker image rebuild (faster restarts)")
@click.option("--skip-generate", is_flag=True, help="Run only the learning flow, skip dashboard generation")
@click.option("--open-browser/--no-open-browser", default=True, help="Open the generated dashboard")
@click.option("--prompt", "-p", default=None, help="Custom incident prompt for generation")
def demo(tear_down: bool, no_build: bool, skip_generate: bool, open_browser: bool, prompt: str | None):
    """Run the checkout-incident demo end to end with one command.

    Boots the local Grafana + Prometheus + fake-metrics stack, teaches Tacit
    from a known-good incident dashboard, then generates a fresh investigation
    dashboard from a plain-English prompt.

    Works with ZERO API keys: without an LLM key Tacit classifies the incident
    deterministically and compiles the dashboard through the archetype engine.
    """
    from tacit import demo_flow

    root = demo_flow.find_repo_root()
    if root is None:
        _fail("Could not find the Tacit demo stack (docker-compose.dev.yml + demo/).")
        _info("Run this from a Tacit checkout, or set TACIT_REPO=/path/to/tacit:")
        _info("  git clone https://github.com/aditki/tacit && cd tacit && tacit demo")
        raise SystemExit(1)

    if tear_down:
        _header("Tearing down demo stack")
        demo_flow.compose_down(root, echo=_info)
        _success("Demo stack stopped")
        return

    _header("Tacit demo — checkout incident in a box")
    _info(f"Using checkout at {root}")
    _info("This stack uses intentionally unsafe local Grafana defaults. Keep it local-only.")
    demo_flow.load_demo_env(root)

    try:
        # 1. Boot the stack
        _header("1/4 Starting local stack (Grafana, Prometheus, fake metrics, Tacit)")
        demo_flow.compose_up(root, echo=_info, build=not no_build)
        _info("Waiting for services to become healthy...")
        demo_flow.wait_for_http(f"{demo_flow.DEFAULT_GRAFANA_URL}/api/health", echo=_info)
        _success("Grafana is up")
        demo_flow.wait_for_http(f"{demo_flow.DEFAULT_API_URL}/healthz", echo=_info)
        _success("Tacit API is up")

        # 2. Learning flow
        _header("2/4 Teaching Tacit from a known-good incident dashboard")
        dashboard_json = root / "demo" / "checkout-service-incident.grafana.json"
        demo_flow.run_learning_flow(demo_flow.DEFAULT_API_URL, dashboard_json, echo=_success)

        if skip_generate:
            _header("Done (generation skipped)")
            _info(f"Web UI:  {demo_flow.DEFAULT_API_URL}")
            _info(f"Grafana: {demo_flow.DEFAULT_GRAFANA_URL}")
            return

        # 3. Generate an investigation dashboard
        _header("3/4 Generating a fresh investigation dashboard from plain English")
        incident_prompt = prompt or demo_flow.DEMO_PROMPT
        _info(f'Prompt: "{incident_prompt[:100]}..."')
        result = demo_flow.run_generation(demo_flow.DEFAULT_API_URL, incident_prompt, echo=_info)

        dashboard_url = result.get("dashboard_url", "")
        if not dashboard_url:
            _fail("Pipeline completed but returned no dashboard URL.")
            _info(f"Summary: {result.get('summary', 'n/a')}")
            raise SystemExit(1)

        _success(f"Dashboard created: {result.get('panel_count', '?')} validated panels")
        _info(dashboard_url)
        demo_flow.record_demo_feedback(demo_flow.DEFAULT_API_URL, result.get("dashboard_uid", ""))

        # 4. Wrap up
        _header("4/4 Demo complete")
        _info(f"Dashboard: {dashboard_url}")
        _info(f"Web UI:    {demo_flow.DEFAULT_API_URL} (watch the live pipeline stages)")
        _info(f"History:   {demo_flow.DEFAULT_API_URL} → History tab")
        _info("Tear down anytime with: tacit demo --down")
        if open_browser:
            webbrowser.open(dashboard_url)

    except demo_flow.DemoError as exc:
        _fail(str(exc))
        raise SystemExit(1)


# ── tacit assess ─────────────────────────────────────────────────────────
@cli.command()
@click.option("--json", "as_json", is_flag=True, help="Emit the raw assessment as JSON")
@click.option("--llm", "with_llm", is_flag=True, help="Add an LLM narrative on top of the deterministic report")
def assess(as_json: bool, with_llm: bool):
    """Operational knowledge assessment — fully deterministic, zero API keys.

    Reports what Tacit has ingested, extracted, resolved, and failed to
    resolve: counts, coverage, staleness, unresolved entities, artifact
    yield, duplicate dashboards, alerts without owners, runbooks without
    matching signals, and investigation activity.

    Add --llm for an optional narrative (requires a configured LLM key).
    """
    _load_env()
    from tacit.assess import build_assessment

    report = build_assessment()

    if as_json:
        import json as json_module

        click.echo(json_module.dumps(report, indent=2, default=str))
        return

    inventory = report["inventory"]
    services = report["services"]
    coverage = report["coverage"]
    quality = report["quality"]
    activity = report["activity"]
    readiness = report["readiness"]

    _header("Operational Knowledge Assessment")

    def _row(label: str, value: Any) -> None:
        console.print(f"  {label:<38} {value}")

    console.print("\n  [bold]Inventory[/]" if Table else "\n  Inventory")
    _row("Services known:", services["known"])
    _row("Dashboards ingested:", inventory["dashboards_ingested"])
    _row("Alerts ingested:", inventory["alerts_ingested"])
    _row("Runbooks learned:", inventory["runbooks"])
    _row("Incidents learned:", inventory["incidents"])
    _row("Signal types:", inventory["signal_types"])
    _row("Metric mappings:", inventory["metric_mappings"])

    console.print("\n  [bold]Coverage & Trust[/]" if Table else "\n  Coverage & Trust")
    _row("Knowledge coverage:", f"{coverage['knowledge_coverage_pct']}%")
    _row(
        "Signals with trusted mappings:",
        f"{coverage['signal_types_with_trusted_mapping']}/{coverage['signal_types_total']}",
    )
    _row("Signals stuck at candidate:", coverage["signal_types_candidate_only"])
    _row("Missing ownership:", services["missing_ownership"])

    console.print("\n  [bold]Knowledge Quality[/]" if Table else "\n  Knowledge Quality")
    _row("Duplicate dashboard groups:", quality["duplicate_groups"])
    _row("Alerts without owner attribution:", quality["alerts_without_owner_attribution"])
    _row("Runbooks without matching signals:", quality["runbooks_without_matching_signals"])
    _row("Incident RCA claims rejected/ignored:", quality["incident_rca_claims_rejected_or_ignored"])
    _row("RCA claims unreviewed >30d:", quality["incident_rca_claims_unreviewed_over_30d"])
    _row("Unresolved evidence claims:", quality["unresolved_evidence_claims"])
    _row("Stale artifacts / alerts:", f"{inventory['artifacts_stale']} / {inventory['alerts_stale']}")
    _row("Artifacts with zero extractions:", quality["artifacts_with_zero_extractions"])
    _row("Avg extractions per artifact:", quality["avg_extractions_per_artifact"])

    console.print("\n  [bold]Activity[/]" if Table else "\n  Activity")
    _row("Investigations run:", activity["investigations_total"])
    _row("Success rate:", f"{activity['success_rate_pct']}%")
    _row("Archetype vs freeform path:", f"{activity['archetype_path']} / {activity['freeform_path']}")

    console.print()
    level = readiness["level"]
    color = {"High": "green", "Medium": "yellow", "Low": "red"}.get(level, "white")
    if Table:
        console.print(f"  [bold]Investigation Readiness:[/] [bold {color}]{level}[/] ({readiness['score']}/100)")
    else:
        console.print(f"  Investigation Readiness: {level} ({readiness['score']}/100)")
    for reason in readiness["reasons"]:
        _info(reason)

    console.print()
    _info("Share safely with: tacit export-report --anonymous")

    if with_llm:
        from tacit.agents.intent_fallback import zero_key_mode
        from tacit.config import settings as runtime_settings

        if zero_key_mode(runtime_settings):
            _warn("--llm requires a configured LLM API key; the deterministic report above is complete without it.")
            return
        _header("LLM Narrative")
        import asyncio

        from tacit.assess import narrate_assessment

        try:
            narrative = asyncio.run(narrate_assessment(report))
            console.print(f"  {narrative}")
        except Exception as exc:
            _fail(f"LLM narrative failed: {exc}")


# ── tacit learn ──────────────────────────────────────────────────────────
@cli.group()
def learn():
    """Learn operational language from existing dashboards."""
    pass


@learn.command("dashboard")
@click.argument("dashboard_uid")
@click.option("--backend", default="", help="Backend name, e.g. grafana or signalfx")
@click.option("--auto-approve/--pending", default=False, help="Immediately activate eligible mappings")
def learn_dashboard(dashboard_uid: str, backend: str, auto_approve: bool):
    """Ingest a dashboard and show what Tacit learned."""
    _header("Learn Dashboard")
    _load_env()

    import asyncio

    async def _run():
        from tacit.dashboard_ingest import ingest_dashboard

        return await ingest_dashboard(
            dashboard_uid=dashboard_uid,
            backend_name=backend,
            auto_approve=auto_approve,
        )

    try:
        result = asyncio.run(_run())
    except Exception as e:
        _fail(f"Dashboard ingestion failed: {e}")
        _info("Run `tacit doctor` to check backend connectivity.")
        return

    quality = result.get("signal_quality", {})
    impact = result.get("learning_impact", {})
    _success(f"Ingested {result.get('dashboard_title') or dashboard_uid}")
    _info(f"Status: {result.get('status', 'pending')}")
    _info(f"Panels: {result.get('panel_count', 0)}")
    _info(f"Metrics found: {len(result.get('metrics_found', []))}")
    _info(f"Signals inferred: {len(result.get('signals_inferred', []))}")
    _info(
        "Learning impact: "
        f"{impact.get('active_mappings_before_learning', 0)} active before, "
        f"{impact.get('candidate_mappings_pending_approval', 0)} candidate pending approval, "
        f"{impact.get('new_active_mappings_after_approval', 0)} newly active"
    )
    if quality:
        _info(
            "Inference quality: "
            f"{quality.get('taxonomy_matches', 0)} taxonomy, "
            f"{quality.get('heuristic_candidates', 0)} heuristic, "
            f"{quality.get('held_for_review', 0)} held for review"
        )
    explanations = quality.get("explanations", [])[:8]
    if explanations:
        _info("Top inferred mappings:")
        for item in explanations:
            confidence = round(item.get("confidence", 0.0) * 100)
            review = item.get("review_state", "")
            _info(
                f"  {item.get('signal_type', 'unknown')} <- {item.get('metric', '')} "
                f"({confidence}%, {item.get('source', '')}, {review})"
            )
            if item.get("reason"):
                _info(f"    {item['reason']}")
    if auto_approve:
        _info(f"Mappings created: {result.get('mappings_created', 0)}")


def _print_bulk_learning_summary(result: dict):
    _success(f"Learned from {result.get('dashboards_learned', 0)} {result.get('backend')} dashboards")
    _info(f"Dashboards discovered: {result.get('dashboards_discovered', 0)}")
    _info(f"Dashboards failed: {result.get('dashboards_failed', 0)}")
    _info(f"Metrics found: {result.get('metrics_found', 0)}")
    _info(f"Signals inferred: {result.get('signals_inferred', 0)}")
    _info(f"Indexed context rows: {result.get('indexed_context_rows', 0)}")
    if result.get("auto_approve"):
        _info(f"Mappings created: {result.get('mappings_created', 0)}")
        _info(f"Archetypes registered: {result.get('archetypes_registered', 0)}")

    learned = result.get("learned", [])
    if learned:
        _info("Top learned dashboards:")
        for item in learned[:10]:
            _info(
                f"  • {item.get('dashboard_title') or item.get('dashboard_uid')} "
                f"({item.get('metrics_found', 0)} metrics, "
                f"{item.get('signals_inferred', 0)} signals, "
                f"{item.get('indexed_context_rows', 0)} indexed rows)"
            )

    failures = result.get("failures", [])
    if failures:
        _info("Failures:")
        for item in failures[:5]:
            _fail(f"  {item.get('dashboard_uid')}: {item.get('error')}")


def _print_bulk_alert_learning_summary(result: dict):
    prefix = "Previewed" if result.get("dry_run") else "Learned from"
    _success(f"{prefix} {result.get('alerts_learned', 0)} {result.get('backend')} alerts")
    _info(f"Alerts discovered: {result.get('alerts_discovered', 0)}")
    _info(f"Alerts failed: {result.get('alerts_failed', 0)}")
    _info(f"Metrics found: {result.get('metrics_found', 0)}")
    _info(f"Signals inferred: {result.get('signals_inferred', 0)}")
    _info(f"Indexed context rows: {result.get('indexed_context_rows', 0)}")
    if result.get("stale_marked", 0):
        _info(f"Alerts marked stale: {result.get('stale_marked', 0)}")
    summary = result.get("summary", {})
    if summary:
        unmapped = max(0, result.get("alerts_learned", 0) - summary.get("signals_mapped", 0))
        _info(
            "Preview: "
            f"{result.get('alerts_discovered', 0)} discovered, "
            f"{summary.get('signals_mapped', 0)} mapped to known signals, "
            f"{summary.get('runbooks_found', 0)} with runbook links, "
            f"{summary.get('ownership_hints', 0)} with ownership/team labels, "
            f"{unmapped} unmapped"
        )
    if result.get("auto_approve"):
        _info(f"Mappings created: {result.get('mappings_created', 0)}")

    learned = result.get("learned", [])
    if learned:
        _info("Top learned alerts:")
        for item in learned[:10]:
            _info(
                f"  • {item.get('alert_title') or item.get('alert_uid')} "
                f"({item.get('metrics_found', 0)} metrics, "
                f"{item.get('signals_inferred', 0)} signals, "
                f"{item.get('indexed_context_rows', 0)} indexed rows)"
            )

    failures = result.get("failures", [])
    if failures:
        _info("Failures:")
        for item in failures[:5]:
            _fail(f"  {item.get('alert_uid')}: {item.get('error')}")


def _print_artifact_learning_summary(result: dict):
    summary = result.get("summary", {})
    action = "Previewed" if result.get("dry_run") else "Learned from"
    artifact_type = result.get("artifact_type") or summary.get("artifact_type") or "artifact"
    if "artifacts_discovered" in result:
        _success(f"{action} {result.get('artifacts_discovered', 0)} {artifact_type}s")
        if result.get("stale_marked", 0):
            _info(f"{artifact_type.title()}s marked stale: {result.get('stale_marked', 0)}")
    else:
        _success(f"{action} {result.get('title', artifact_type)}")
        _info(f"Status: {result.get('change_state', 'dry_run')}")
    if summary:
        _info(
            "Extracted: "
            f"{summary.get('evidence_requirements', 0)} evidence requirements, "
            f"{summary.get('ownership_hints', 0)} ownership hints, "
            f"{summary.get('dependency_hints', 0)} dependency hints, "
            f"{summary.get('signal_mapping_candidates', 0)} signal candidates"
        )
    warnings = summary.get("warnings", []) if summary else result.get("warnings", [])
    if warnings:
        _info(f"Warnings: {len(warnings)}")
        for warning in warnings[:5]:
            _warn(str(warning))


@learn.command("runbooks")
@click.option("--file", "file_path", type=click.Path(exists=True, dir_okay=False, path_type=Path), help="Runbook file")
@click.option(
    "--dir", "dir_path", type=click.Path(exists=True, file_okay=False, path_type=Path), help="Runbook directory"
)
@click.option("--dry-run", is_flag=True, help="Preview extraction without persisting learned context")
def learn_runbooks(file_path: Path | None, dir_path: Path | None, dry_run: bool):
    """Learn operational candidates from runbook artifacts."""
    _header("Learn Runbooks")
    _load_env()
    if bool(file_path) == bool(dir_path):
        _fail("Pass exactly one of --file or --dir.")
        return
    try:
        if file_path:
            from tacit.artifact_learning import learn_runbook_file

            result = learn_runbook_file(file_path, dry_run=dry_run)
        else:
            from tacit.artifact_learning import learn_runbook_dir

            result = learn_runbook_dir(dir_path, dry_run=dry_run)  # type: ignore[arg-type]
    except Exception as e:
        _fail(f"Runbook learning failed: {e}")
        return
    _print_artifact_learning_summary(result)


@learn.command("incidents")
@click.option("--file", "file_path", type=click.Path(exists=True, dir_okay=False, path_type=Path), help="Incident file")
@click.option(
    "--dir", "dir_path", type=click.Path(exists=True, file_okay=False, path_type=Path), help="Incident directory"
)
@click.option("--dry-run", is_flag=True, help="Preview extraction without persisting learned context")
def learn_incidents(file_path: Path | None, dir_path: Path | None, dry_run: bool):
    """Learn operational IR candidates from incident history artifacts."""
    _header("Learn Incidents")
    _load_env()
    if bool(file_path) == bool(dir_path):
        _fail("Pass exactly one of --file or --dir.")
        return
    try:
        if file_path:
            from tacit.artifact_learning import learn_incident_file

            result = learn_incident_file(file_path, dry_run=dry_run)
        else:
            from tacit.artifact_learning import learn_incident_dir

            result = learn_incident_dir(dir_path, dry_run=dry_run)  # type: ignore[arg-type]
    except Exception as e:
        _fail(f"Incident learning failed: {e}")
        return
    _print_artifact_learning_summary(result)


@learn.command("pagerduty")
@click.option(
    "--since",
    required=True,
    help="ISO8601 start of the incident window (required: without it the "
    "PagerDuty API silently returns only its default recent window, not history)",
)
@click.option("--until", default=None, help="ISO8601 end of the incident window (default: now)")
@click.option(
    "--status",
    "statuses",
    multiple=True,
    default=("resolved",),
    show_default=True,
    help="Incident status filter (repeatable): triggered, acknowledged, resolved",
)
@click.option("--limit", default=1000, show_default=True, type=click.IntRange(min=1), help="Maximum incidents to fetch")
@click.option("--dry-run", is_flag=True, help="Preview extraction without persisting learned context")
def learn_pagerduty(since: str, until: str | None, statuses: tuple[str, ...], limit: int, dry_run: bool):
    """Learn incident metadata from PagerDuty (read-only)."""
    _header("Learn PagerDuty Incidents")
    _load_env()

    import asyncio

    async def _run():
        from tacit.integrations.pagerduty import PagerDutyClient, learn_pagerduty_incidents

        async with PagerDutyClient() as client:
            return await learn_pagerduty_incidents(
                client,
                statuses=list(statuses),
                since=since,
                until=until,
                max_items=limit,
                dry_run=dry_run,
            )

    try:
        result = asyncio.run(_run())
    except Exception as e:
        _fail(f"PagerDuty learning failed: {e}")
        raise SystemExit(1) from e
    _print_artifact_learning_summary(result)


@learn.command("alerts")
@click.option("--from", "source", default="grafana", show_default=True, help="Backend source: grafana or signalfx")
@click.option("--uid", "alert_uid", default="", help="Ingest one alert UID instead of crawling all alerts")
@click.option("--auto-approve/--pending", default=False, help="Immediately activate eligible mappings")
@click.option("--dry-run", is_flag=True, help="Preview alert ingestion without persisting learned context")
@click.option("--limit", default=500, show_default=True, help="Maximum alerts to crawl")
def learn_alerts(source: str, alert_uid: str, auto_approve: bool, dry_run: bool, limit: int):
    """Crawl or preview alert rules from a backend."""
    _header(f"Learn {source.title()} Alerts")
    _load_env()

    import asyncio

    async def _run():
        if alert_uid:
            from tacit.alert_ingest import ingest_alert

            return await ingest_alert(
                alert_uid=alert_uid,
                backend_name=source,
                auto_approve=auto_approve,
                dry_run=dry_run,
            )
        from tacit.alert_ingest import learn_backend_alerts

        return await learn_backend_alerts(
            source,
            auto_approve=auto_approve,
            dry_run=dry_run,
            limit=limit,
        )

    try:
        result = asyncio.run(_run())
    except Exception as e:
        _fail(f"Alert ingestion failed: {e}")
        _info("Run `tacit doctor` to check backend connectivity.")
        return

    if "alerts_learned" in result:
        _print_bulk_alert_learning_summary(result)
        return

    quality = result.get("signal_quality", {})
    action = "Previewed" if dry_run else "Ingested"
    _success(f"{action} {result.get('alert_title') or alert_uid}")
    _info(f"Status: {result.get('status', 'pending')}")
    _info(f"Metrics found: {len(result.get('metrics_found', []))}")
    _info(f"Signals inferred: {len(result.get('signals_inferred', []))}")
    _info(f"Indexed context rows: {result.get('indexed_context_rows', 0)}")
    summary = result.get("summary", {})
    if summary:
        _info(
            "Summary: "
            f"{summary.get('signals_mapped', 0)} mapped, "
            f"{summary.get('runbooks_found', 0)} runbook links, "
            f"{summary.get('ownership_hints', 0)} ownership/team hints"
        )
    if quality:
        _info(
            "Inference quality: "
            f"{quality.get('taxonomy_matches', 0)} taxonomy, "
            f"{quality.get('heuristic_candidates', 0)} heuristic, "
            f"{quality.get('held_for_review', 0)} held for review"
        )
    if auto_approve and not dry_run:
        _info(f"Mappings created: {result.get('mappings_created', 0)}")


def _run_backend_learning(backend_name: str, auto_approve: bool, limit: int):
    _header(f"Learn {backend_name.title()} Dashboards")
    _load_env()

    import asyncio

    async def _run():
        from tacit.dashboard_ingest import learn_backend_dashboards

        return await learn_backend_dashboards(
            backend_name,
            auto_approve=auto_approve,
            limit=limit,
        )

    try:
        result = asyncio.run(_run())
    except Exception as e:
        _fail(f"Bulk learning failed: {e}")
        _info("Run `tacit doctor` to check backend connectivity.")
        return

    _print_bulk_learning_summary(result)


@learn.command("grafana")
@click.option("--auto-approve/--pending", default=False, help="Immediately activate eligible mappings")
@click.option("--limit", default=500, show_default=True, help="Maximum dashboards to crawl")
def learn_grafana(auto_approve: bool, limit: int):
    """Crawl Grafana dashboards and persist learned operational context."""
    _run_backend_learning("grafana", auto_approve, limit)


@learn.command("signalfx")
@click.option("--auto-approve/--pending", default=False, help="Immediately activate eligible mappings")
@click.option("--limit", default=500, show_default=True, help="Maximum dashboards to crawl")
def learn_signalfx(auto_approve: bool, limit: int):
    """Crawl SignalFx dashboards and persist learned operational context."""
    _run_backend_learning("signalfx", auto_approve, limit)


@learn.command("approve")
@click.argument("dashboard_uid")
@click.option("--backend", default="", help="Backend name, e.g. grafana_json or signalfx")
def learn_approve(dashboard_uid: str, backend: str):
    """Approve a pending learned dashboard and activate mappings."""
    _header("Approve Learned Dashboard")
    _load_env()

    from tacit.dashboard_ingest import approve_ingested_dashboard_record

    try:
        result = approve_ingested_dashboard_record(
            dashboard_uid=dashboard_uid,
            backend_name=backend or None,
        )
    except LookupError:
        _fail("Ingested dashboard not found")
        return

    if result.get("status") == "approved":
        _success(result.get("message", "Dashboard approved"))
        _info(f"Mappings created: {result.get('mappings_created', 0)}")
        _info(f"Archetype registered: {result.get('archetype_registered', False)}")
    else:
        _info(result.get("message", f"Dashboard already {result.get('status')}"))


@learn.command("reject")
@click.argument("dashboard_uid")
@click.option("--backend", default="", help="Backend name, e.g. grafana_json or signalfx")
def learn_reject(dashboard_uid: str, backend: str):
    """Reject a pending learned dashboard and remove it from default retrieval."""
    _header("Reject Learned Dashboard")
    _load_env()

    from tacit.dashboard_ingest import reject_ingested_dashboard_record

    try:
        result = reject_ingested_dashboard_record(
            dashboard_uid=dashboard_uid,
            backend_name=backend or None,
        )
    except LookupError:
        _fail("Ingested dashboard not found or not pending")
        return
    except RuntimeError:
        _fail("Dashboard is no longer pending")
        return

    if result.get("status") == "rejected":
        _success(result.get("message", "Dashboard rejected"))
        _info(f"Rejected candidates recorded: {result.get('rejected_candidates', 0)}")
    else:
        _info(result.get("message", f"Dashboard already {result.get('status')}"))


@learn.command("ignore")
@click.argument("dashboard_uid")
@click.option("--backend", default="", help="Backend name, e.g. grafana_json or signalfx")
def learn_ignore(dashboard_uid: str, backend: str):
    """Ignore a pending learned dashboard without negative training data."""
    _header("Ignore Learned Dashboard")
    _load_env()

    from tacit.signals import get_signal_store

    store = get_signal_store()
    if store.ignore_ingested_dashboard(dashboard_uid, backend_name=backend or None):
        _success("Dashboard ignored")
    else:
        _fail("Ingested dashboard not found or not pending")


@learn.command("search")
@click.argument("query")
@click.option("--service", default="", help="Optional service/component filter")
@click.option("--approved-only", is_flag=True, help="Only show approved/trusted context")
@click.option("--limit", default=10, show_default=True, help="Maximum context rows")
def learn_search(query: str, service: str, approved_only: bool, limit: int):
    """Search learned dashboards, panels, metrics, and signal mappings."""
    _header("Search Learned Context")
    _load_env()

    from tacit.signals import LearningIndexUnavailable, get_signal_store

    store = get_signal_store()
    try:
        rows = store.search_learning_context(
            query,
            service=service,
            include_candidates=not approved_only,
            limit=limit,
        )
    except LearningIndexUnavailable as e:
        _fail(str(e))
        return
    if not rows:
        _info("No learned context matched.")
        return

    for row in rows:
        state = row.get("review_state", "candidate")
        _info(
            f"• {row.get('metric_name', '')} → {row.get('signal_type', '') or 'unclassified'} "
            f"({state}, {row.get('dashboard_title', '')} / {row.get('panel_title', '')})"
        )
        if row.get("reason"):
            _info(f"  {row['reason']}")


@learn.command("service")
@click.argument("service")
@click.option("--approved-only", is_flag=True, help="Only use approved/trusted context")
@click.option("--limit", default=50, show_default=True, help="Maximum context rows")
def learn_service(service: str, approved_only: bool, limit: int):
    """Describe a service from learned operational context."""
    _header(f"Service Context: {service}")
    _load_env()

    from tacit.signals import LearningIndexUnavailable, get_signal_store

    try:
        summary = get_signal_store().describe_service(
            service,
            include_candidates=not approved_only,
            limit=limit,
        )
    except LearningIndexUnavailable as e:
        _fail(str(e))
        return
    _info(f"Matched context rows: {summary.get('matched_context_rows', 0)}")
    _info(f"Trusted rows: {summary.get('trusted_context_rows', 0)}")
    _info(f"Candidate rows: {summary.get('candidate_context_rows', 0)}")

    dashboards = summary.get("dashboards", [])
    if dashboards:
        _info("Dashboards:")
        for dashboard in dashboards[:8]:
            _info(
                f"  • {dashboard.get('dashboard_title') or dashboard.get('dashboard_uid')} "
                f"({dashboard.get('backend_name')}, {dashboard.get('review_state')})"
            )

    metrics = summary.get("top_metrics", [])
    if metrics:
        _info("Metrics:")
        for metric in metrics[:10]:
            signals = ", ".join(metric.get("signal_types", [])) or "unclassified"
            states = ", ".join(metric.get("review_states", []))
            _info(f"  • {metric.get('metric')} → {signals} ({states})")

    signals = summary.get("signals", {})
    if signals:
        _info("Signals:")
        for signal, count in list(signals.items())[:10]:
            _info(f"  • {signal}: {count}")


# ── tacit serve ──────────────────────────────────────────────────────────
@cli.command()
@click.option("--host", default="0.0.0.0", help="Bind host")
@click.option("--port", "-p", default=8000, type=int, help="Bind port")
@click.option("--reload", is_flag=True, help="Enable auto-reload (dev mode)")
@click.option("--no-slack", is_flag=True, help="Disable Slack integration")
def serve(host: str, port: int, reload: bool, no_slack: bool):
    """Start the Tacit API server."""
    _load_env()

    if no_slack:
        os.environ["SLACK_BOT_TOKEN"] = ""
        os.environ["SLACK_APP_TOKEN"] = ""

    _header(f"Tacit Server — {host}:{port}")

    import uvicorn

    from tacit.config import settings
    from tacit.logging import configure_logging

    configure_logging(settings.log_level)

    _info(f"LLM: {settings.llm_provider} / {settings.llm_model}")
    _info(f"Grafana: {settings.grafana_url}")
    _info(f"Log level: {settings.log_level}")
    if settings.slack_bot_token:
        _info("Slack: enabled")
    else:
        _info("Slack: disabled")
    if settings.signalfx_enabled:
        _info(f"SignalFx: enabled (realm={settings.signalfx_realm})")
    else:
        _info("SignalFx: disabled")
    console.print()

    uvicorn.run(
        "tacit.main:app",
        host=host,
        port=port,
        reload=reload,
        log_level=settings.log_level.lower(),
    )


@cli.command("export-report")
@click.option("--anonymous", is_flag=True, help="Create a shareable anonymized assessment bundle")
@click.option("--output", type=click.Path(dir_okay=False, path_type=Path), default=None, help="Output tar.gz path")
@click.option("--validate", "validate_bundle", is_flag=True, help="Fail if anonymous leakage checks find issues")
def export_report(anonymous: bool, output: Path | None, validate_bundle: bool):
    """Export a local or anonymous Tacit assessment bundle."""
    _header("Export Assessment Report")
    _load_env()

    from tacit.export_report import export_assessment_report

    try:
        result = export_assessment_report(output=output, anonymous=anonymous, validate=validate_bundle)
    except ValueError as exc:
        _fail(str(exc))
        raise click.ClickException(str(exc)) from exc

    _success(f"Report written: {result.output_path}")
    _info(f"Files: {len(result.files)}")
    if anonymous:
        _info("Anonymous bundle excludes raw artifact text and anonymization mappings.")
        validation = result.validation_report
        if validation.get("passed"):
            _success("Leakage validation passed")
        else:
            _warn(f"Leakage validation findings: {validation.get('findings_count', 0)}")
    else:
        _info("Leakage validation skipped for raw local export.")


# ── tacit history ─────────────────────────────────────────────────────
@cli.group()
def history():
    """View investigation history and pipeline telemetry."""
    pass


@history.command("list")
@click.option("--limit", "-n", default=20, type=int, help="Number of records")
@click.option("--status", type=click.Choice(["success", "failed", "timeout"]), default=None)
@click.option("--user", default=None, help="Filter by user ID")
def history_list(limit: int, status: str | None, user: str | None):
    """List recent investigations."""
    _load_env()
    from tacit.history import get_investigation_store

    store = get_investigation_store()
    investigations = store.list_recent(limit=limit, status=status, user_id=user)

    if not investigations:
        _info("No investigations found.")
        return

    if Table is not None:
        table = Table(title=f"Recent Investigations ({len(investigations)})")
        table.add_column("ID", style="dim", width=16)
        table.add_column("Status", width=8)
        table.add_column("Prompt", max_width=40)
        table.add_column("Path", width=10)
        table.add_column("Panels", justify="right", width=6)
        table.add_column("Time", justify="right", width=7)
        table.add_column("Archetypes", max_width=30)

        for inv in investigations:
            status_style = {
                "success": "[green]success[/]",
                "failed": "[red]failed[/]",
                "timeout": "[yellow]timeout[/]",
            }.get(inv["status"], inv["status"])

            archetypes = inv.get("archetypes", [])
            arch_str = ", ".join(f"{a['type']}({a['confidence']:.0%})" for a in archetypes[:2]) if archetypes else "—"

            table.add_row(
                inv["id"],
                status_style,
                (inv["prompt"][:37] + "...") if len(inv["prompt"]) > 40 else inv["prompt"],
                inv.get("path_used", "—"),
                str(inv.get("panel_count", 0)),
                f"{inv.get('total_time', 0):.1f}s",
                arch_str,
            )
        console.print(table)
    else:
        for inv in investigations:
            click.echo(f"  {inv['id']}  {inv['status']:8s}  {inv['prompt'][:50]}")


@history.command("show")
@click.argument("investigation_id")
def history_show(investigation_id: str):
    """Show full details of a single investigation."""
    _load_env()
    from tacit.history import get_investigation_store

    store = get_investigation_store()
    inv = store.get(investigation_id)

    if inv is None:
        _fail(f"Investigation {investigation_id} not found")
        return

    _header(f"Investigation {inv['id']}")

    # Status
    status = inv["status"]
    if status == "success":
        _success(f"Status: {status}")
    elif status == "failed":
        _fail(f"Status: {status} — {inv.get('error', '')}")
    else:
        _warn(f"Status: {status}")

    console.print()
    _info(f"Prompt: {inv['prompt']}")
    _info(f"User: {inv.get('user_id', '—')}")
    _info(f"Time: {inv.get('total_time', 0):.2f}s")

    # Intent
    console.print()
    _header("Intent")
    _info(f"Summary: {inv.get('intent_summary', '—')}")
    _info(f"Domain: {inv.get('intent_domain', '—')}")
    _info(f"Services: {inv.get('intent_services', [])}")
    _info(f"Keywords: {inv.get('intent_keywords', [])}")
    _info(f"Problem type: {inv.get('problem_type', '—')}")
    archetypes = inv.get("archetypes", [])
    if archetypes:
        arch_str = ", ".join(f"{a['type']} ({a['confidence']:.0%})" for a in archetypes)
        _info(f"Archetypes: {arch_str}")

    # Discovery
    console.print()
    _header("Discovery")
    _info(f"Datasources: {inv.get('datasources_found', 0)} ({inv.get('datasource_types', [])})")
    _info(f"Metric catalog: {inv.get('metrics_catalog_size', 0)} metrics")
    _info(f"After ranking: {inv.get('metrics_ranked_size', 0)} metrics")
    _info(f"Selected: {inv.get('metrics_selected', [])}")

    # Queries
    console.print()
    _header("Queries")
    _info(f"Path: {inv.get('path_used', '—')}")
    _info(f"Panels: {inv.get('panel_count', 0)}")
    queries = inv.get("generated_queries", [])
    for q in queries[:10]:
        _info(f"  [{q.get('panel_title', '?')}] {q.get('expr', '')[:80]}")
    if len(queries) > 10:
        _info(f"  ... and {len(queries) - 10} more")

    # Validation
    warnings = inv.get("validation_warnings", [])
    if warnings:
        console.print()
        _header("Validation")
        _info(f"Panels dropped: {inv.get('panels_dropped', 0)}")
        for w in warnings[:5]:
            _warn(w)

    # Timings
    timings = inv.get("timings", {})
    if timings:
        console.print()
        _header("Timings")
        for step, secs in timings.items():
            _info(f"  {step}: {secs:.2f}s")

    # Result
    if inv.get("dashboard_url"):
        console.print()
        _success(f"Dashboard: {inv['dashboard_url']}")


@history.command("stats")
def history_stats():
    """Show aggregate investigation statistics."""
    _load_env()
    from tacit.history import get_investigation_store

    store = get_investigation_store()
    s = store.stats()

    _header("Investigation Stats")
    total = s.get("total", 0)
    if total == 0:
        _info("No investigations recorded yet.")
        return

    _info(f"Total: {total}")
    _success(f"Succeeded: {s.get('succeeded', 0)}")
    _fail(f"Failed: {s.get('failed', 0)}")
    _warn(f"Timed out: {s.get('timed_out', 0)}")
    console.print()
    _info(f"Avg time: {s.get('avg_time', 0):.2f}s")
    _info(f"Avg panels: {s.get('avg_panels', 0):.1f}")
    _info(f"Avg catalog size: {s.get('avg_catalog_size', 0):.0f} metrics")
    console.print()
    _info(f"Archetype path: {s.get('archetype_path', 0)}")
    _info(f"Freeform path: {s.get('freeform_path', 0)}")


# ── Entry point ──────────────────────────────────────────────────────────────
def main():
    cli()


if __name__ == "__main__":
    main()
