"""DashForge CLI — single-command local startup for on-call engineers."""

from __future__ import annotations

import os
import webbrowser
from collections.abc import Callable
from concurrent.futures import Future
from pathlib import Path
from typing import Any

import click
import yaml

# ── Constants ────────────────────────────────────────────────────────────────
DASHFORGE_HOME = Path.home() / ".dashforge"
CONFIG_FILE = DASHFORGE_HOME / "config.yaml"


def _get_version() -> str:
    """Derive version from package metadata to avoid drift with pyproject.toml."""
    # 1. Try installed package metadata (works after pip install -e .)
    try:
        from importlib.metadata import version

        return version("dashforge")
    except Exception:
        pass
    # 2. Fallback: parse pyproject.toml directly (running from source)
    try:
        import re

        toml_path = Path(__file__).resolve().parent.parent / "pyproject.toml"
        if toml_path.exists():
            match = re.search(r'^version\s*=\s*"([^"]+)"', toml_path.read_text(), re.MULTILINE)
            if match:
                return match.group(1)
    except Exception:
        pass
    return "0.0.0-dev"


VERSION = _get_version()

# ── Rich helpers (graceful fallback) ─────────────────────────────────────────
console: Any
Prompt: Any | None
Confirm: Any | None
Table: Any | None

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Confirm as RichConfirm
    from rich.prompt import Prompt as RichPrompt
    from rich.table import Table as RichTable

    console = Console()
    Prompt = RichPrompt
    Confirm = RichConfirm
    Table = RichTable

    def _success(msg: str) -> None:
        console.print(f"  [bold green]✔[/] {msg}")

    def _warn(msg: str) -> None:
        console.print(f"  [bold yellow]⚠[/] {msg}")

    def _fail(msg: str) -> None:
        console.print(f"  [bold red]✘[/] {msg}")

    def _info(msg: str) -> None:
        console.print(f"  [dim]→[/] {msg}")

    def _header(msg: str) -> None:
        console.print(Panel(f"[bold]{msg}[/]", border_style="blue"))

except ImportError:
    # Fallback: plain text
    class _FakeConsole:
        def print(self, msg: str = "", **kw: Any) -> None:
            click.echo(msg)

    console = _FakeConsole()

    def _success(msg: str) -> None:
        click.echo(f"  ✔ {msg}")

    def _warn(msg: str) -> None:
        click.echo(f"  ⚠ {msg}")

    def _fail(msg: str) -> None:
        click.echo(f"  ✘ {msg}")

    def _info(msg: str) -> None:
        click.echo(f"  → {msg}")

    def _header(msg: str) -> None:
        click.echo(f"\n{'─' * 60}\n  {msg}\n{'─' * 60}")

    Prompt = None
    Confirm = None
    Table = None


def _prompt(text: str, default: str = "") -> str:
    """Interactive prompt with Rich fallback."""
    if Prompt is not None:
        return Prompt.ask(f"  {text}", default=default or None) or default
    return click.prompt(f"  {text}", default=default)


def _confirm(text: str, default: bool = True) -> bool:
    if Confirm is not None:
        return Confirm.ask(f"  {text}", default=default)
    return click.confirm(f"  {text}", default=default)


# ── CLI Group ────────────────────────────────────────────────────────────────
@click.group()
@click.version_option(VERSION, prog_name="dashforge")
def cli():
    """DashForge — Natural language → Grafana dashboards."""
    pass


# ── dashforge init ───────────────────────────────────────────────────────────
@cli.command()
@click.option("--non-interactive", is_flag=True, help="Skip prompts, use defaults")
def init(non_interactive: bool):
    """Interactive setup wizard. Creates ~/.dashforge/config.yaml."""
    _header("DashForge Setup")

    if CONFIG_FILE.exists() and not non_interactive:
        if not _confirm("Config already exists. Overwrite?", default=False):
            _info("Keeping existing config.")
            return

    DASHFORGE_HOME.mkdir(parents=True, exist_ok=True)

    if non_interactive:
        config = _default_config()
        _info("Using default config (non-interactive mode)")
    else:
        config = _interactive_setup()

    # Write config (secrets go to .env, not YAML)
    config_data, secrets = _split_config(config)
    with open(CONFIG_FILE, "w") as f:
        f.write("# DashForge configuration — generated by `dashforge init`\n")
        f.write("# Secrets (API keys) are in ~/.dashforge/.env\n\n")
        yaml.dump(config_data, f, default_flow_style=False, sort_keys=False)

    env_path = DASHFORGE_HOME / ".env"
    with open(env_path, "w") as f:
        f.write("# DashForge secrets — generated by `dashforge init`\n")
        for k, v in secrets.items():
            f.write(f"{k}={v}\n")
    env_path.chmod(0o600)

    _success(f"Config written to {CONFIG_FILE}")
    _success(f"Secrets written to {env_path}")
    console.print()
    _info("Next steps:")
    _info("  dashforge doctor   — validate your setup")
    _info("  dashforge test     — run a sample investigation")
    _info("  dashforge serve    — start the API server")


def _default_config() -> dict:
    return {
        "grafana_url": "http://localhost:3000",
        "grafana_api_key": "",
        "grafana_org_id": 1,
        "llm_provider": "anthropic",
        "llm_api_key": "",
        "llm_model": "claude-sonnet-4-20250514",
        "llm_api_base": "",
        "log_level": "INFO",
    }


def _interactive_setup() -> dict:
    config: dict = {}
    console.print()

    # ── Grafana ──
    _header("Grafana Connection")
    config["grafana_url"] = _prompt("Grafana URL", "http://localhost:3000")
    config["grafana_api_key"] = _prompt("Grafana API key (service account token)", "")
    config["grafana_org_id"] = int(_prompt("Grafana Org ID", "1"))

    # ── LLM ──
    console.print()
    _header("LLM Provider")
    config["llm_provider"] = _prompt("Provider (anthropic/openai/azure/bedrock/ollama)", "anthropic")

    if config["llm_provider"] != "bedrock":
        config["llm_api_key"] = _prompt("LLM API key", "")
    else:
        config["llm_api_key"] = ""  # Bedrock uses IAM, not API keys

    model_defaults = {
        "anthropic": "claude-sonnet-4-20250514",
        "openai": "gpt-4o",
        "azure": "gpt-4o",
        "bedrock": "anthropic.claude-sonnet-4-20250514-v1:0",
        "ollama": "llama3",
    }
    default_model = model_defaults.get(config["llm_provider"], "claude-sonnet-4-20250514")
    config["llm_model"] = _prompt("Model name", default_model)

    if config["llm_provider"] in ("azure", "ollama"):
        config["llm_api_base"] = _prompt("API base URL", "")
    elif config["llm_provider"] == "bedrock":
        config["llm_api_base"] = ""
        config["llm_bedrock_region"] = _prompt("AWS region", "us-east-1")
        config["llm_bedrock_role_arn"] = _prompt("IAM role ARN to assume (leave empty for default chain)", "")
        if _confirm("Use explicit AWS access keys? (No = use IAM role/instance profile)", default=False):
            config["llm_aws_access_key_id"] = _prompt("AWS Access Key ID", "")
            config["llm_aws_secret_access_key"] = _prompt("AWS Secret Access Key", "")
    else:
        config["llm_api_base"] = ""

    # ── Slack (optional) ──
    console.print()
    if _confirm("Configure Slack integration?", default=False):
        _header("Slack Integration")
        config["slack_bot_token"] = _prompt("Bot token (xoxb-...)", "")
        config["slack_app_token"] = _prompt("App token (xapp-...)", "")
        config["slack_signing_secret"] = _prompt("Signing secret", "")

    # ── Splunk SignalFx (optional) ──
    console.print()
    if _confirm("Configure Splunk SignalFx (Observability Cloud) integration?", default=False):
        _header("Splunk SignalFx")
        config["signalfx_enabled"] = True
        config["signalfx_api_token"] = _prompt("API token (SFx access token)", "")
        config["signalfx_realm"] = _prompt("Realm (us0, us1, us2, eu0, jp0, au0)", "us1")
        config["signalfx_dashboard_group"] = _prompt("Dashboard group name", "DashForge")
    else:
        config["signalfx_enabled"] = False

    config["log_level"] = "INFO"
    return config


def _split_config(config: dict) -> tuple[dict, dict]:
    """Split config into YAML-safe settings and secrets (.env)."""
    secret_keys = {
        "grafana_api_key": "GRAFANA_API_KEY",
        "llm_api_key": "LLM_API_KEY",
        "slack_bot_token": "SLACK_BOT_TOKEN",
        "slack_app_token": "SLACK_APP_TOKEN",
        "slack_signing_secret": "SLACK_SIGNING_SECRET",
        "signalfx_api_token": "SIGNALFX_API_TOKEN",
        "llm_aws_access_key_id": "LLM_AWS_ACCESS_KEY_ID",
        "llm_aws_secret_access_key": "LLM_AWS_SECRET_ACCESS_KEY",
    }
    yaml_config: dict = {}
    secrets: dict = {}

    for k, v in config.items():
        if k in secret_keys:
            if v:
                secrets[secret_keys[k]] = v
        else:
            yaml_config[k] = v

    # Map non-secret config keys to env-style for the yaml
    structured: dict = {
        "grafana": {
            "url": yaml_config.pop("grafana_url", "http://localhost:3000"),
            "org_id": yaml_config.pop("grafana_org_id", 1),
        },
        "llm": {
            "provider": yaml_config.pop("llm_provider", "anthropic"),
            "model": yaml_config.pop("llm_model", "claude-sonnet-4-20250514"),
        },
    }
    api_base = yaml_config.pop("llm_api_base", "")
    if api_base:
        structured["llm"]["api_base"] = api_base

    # Bedrock config
    bedrock_region = yaml_config.pop("llm_bedrock_region", "")
    bedrock_role_arn = yaml_config.pop("llm_bedrock_role_arn", "")
    if structured["llm"].get("provider") == "bedrock" or bedrock_region:
        if bedrock_region:
            structured["llm"]["bedrock_region"] = bedrock_region
        if bedrock_role_arn:
            structured["llm"]["bedrock_role_arn"] = bedrock_role_arn

    # SignalFx config
    sfx_enabled = yaml_config.pop("signalfx_enabled", False)
    sfx_realm = yaml_config.pop("signalfx_realm", "")
    sfx_group = yaml_config.pop("signalfx_dashboard_group", "")
    if sfx_enabled or sfx_realm:
        structured["signalfx"] = {
            "enabled": sfx_enabled,
        }
        if sfx_realm:
            structured["signalfx"]["realm"] = sfx_realm
        if sfx_group:
            structured["signalfx"]["dashboard_group"] = sfx_group

    structured["log_level"] = yaml_config.pop("log_level", "INFO")

    # Carry over any remaining keys
    structured.update(yaml_config)
    return structured, secrets


# ── dashforge doctor ─────────────────────────────────────────────────────────
@cli.command()
def doctor():
    """Validate Grafana, datasources, LLM connectivity, and cache state."""
    _header("DashForge Doctor")
    _load_env()

    from concurrent.futures import ThreadPoolExecutor, as_completed

    # ── Synchronous local checks (instant) ────────────────────────────
    checks_passed = 0
    checks_total = 0
    fatal_failures: list[str] = []
    warnings: list[str] = []

    # 1. Config file
    checks_total += 1
    if CONFIG_FILE.exists():
        _success(f"Config found: {CONFIG_FILE}")
        checks_passed += 1
    else:
        _warn(f"No config at {CONFIG_FILE} — run `dashforge init`")
        fatal_failures.append("config")

    # 2. Archetypes (local file check, no network)
    checks_total += 1
    arch_ok = _check_archetypes()
    if arch_ok:
        checks_passed += 1
    else:
        warnings.append("archetypes")

    # 3. Cache dir
    checks_total += 1
    data_dir = Path("data")
    if data_dir.exists():
        _success(f"Data directory exists: {data_dir.resolve()}")
        checks_passed += 1
    else:
        _info("Data directory will be created on first run")
        checks_passed += 1  # Not a failure

    # ── Parallel network checks ───────────────────────────────────────
    # Run Grafana, LLM, and SignalFx checks concurrently to reduce wall time
    sfx_enabled = False
    try:
        from dashforge.config import settings as _sfx_settings

        sfx_enabled = _sfx_settings.signalfx_enabled and bool(_sfx_settings.signalfx_api_token)
    except Exception:
        pass

    network_checks: dict[str, Callable[[], bool]] = {
        "grafana": _check_grafana,
        "llm": _check_llm,
    }
    if sfx_enabled:
        network_checks["signalfx"] = _check_signalfx

    network_results: dict[str, bool] = {}
    with ThreadPoolExecutor(max_workers=len(network_checks)) as pool:
        futures: dict[Future[bool], str] = {pool.submit(fn): name for name, fn in network_checks.items()}
        for future in as_completed(futures):
            name = futures[future]
            try:
                network_results[name] = future.result()
            except Exception:
                network_results[name] = False

    grafana_ok = network_results.get("grafana", False)

    checks_total += len(network_checks)
    for name, ok in network_results.items():
        if ok:
            checks_passed += 1
        else:
            fatal_failures.append(name)

    # 4. Datasource discovery (depends on Grafana — sequential)
    if grafana_ok:
        checks_total += 1
        ds_ok = _check_datasources()
        if ds_ok:
            checks_passed += 1
        else:
            warnings.append("datasources")

    # ── Summary with classified failures ──────────────────────────────
    console.print()
    if checks_passed == checks_total:
        _success(f"All {checks_total} checks passed!")
    else:
        _warn(f"{checks_passed}/{checks_total} checks passed")
        if fatal_failures:
            _fail(f"Fatal: {', '.join(fatal_failures)}")
        if warnings:
            _warn(f"Warnings: {', '.join(warnings)}")
        if "grafana" in fatal_failures:
            _info("Run `dashforge connect grafana` to fix Grafana connection")
        if "signalfx" in fatal_failures:
            _info("Run `dashforge connect signalfx` to fix SignalFx connection")
        if "llm" in fatal_failures:
            _info("Check your LLM_API_KEY in ~/.dashforge/.env")


def _load_env():
    """Load ~/.dashforge/.env and point config to ~/.dashforge/config.yaml."""
    env_file = DASHFORGE_HOME / ".env"
    if env_file.exists():
        from dotenv import load_dotenv

        load_dotenv(env_file)

    if CONFIG_FILE.exists() and not os.environ.get("DASHFORGE_CONFIG"):
        os.environ["DASHFORGE_CONFIG"] = str(CONFIG_FILE)


def _check_grafana() -> bool:
    try:
        import httpx

        from dashforge.config import settings

        url = settings.grafana_url.rstrip("/")
        api_key = settings.grafana_api_key

        if not api_key:
            _warn("Grafana: no API key configured")
            return False

        headers = {"Authorization": f"Bearer {api_key}"}
        resp = httpx.get(f"{url}/api/org", headers=headers, timeout=10)
        if resp.status_code == 200:
            org = resp.json()
            _success(f"Grafana: connected to \"{org.get('name', 'unknown')}\" at {url}")
            return True
        else:
            _fail(f"Grafana: HTTP {resp.status_code} from {url}/api/org")
            return False
    except Exception as e:
        _fail(f"Grafana: {e}")
        return False


def _check_datasources() -> bool:
    try:
        import httpx

        from dashforge.config import settings

        url = settings.grafana_url.rstrip("/")
        headers = {"Authorization": f"Bearer {settings.grafana_api_key}"}
        resp = httpx.get(f"{url}/api/datasources", headers=headers, timeout=10)
        if resp.status_code == 200:
            ds_list = resp.json()
            types: dict[str, int] = {}
            for ds in ds_list:
                t = ds.get("type", "unknown")
                types[t] = types.get(t, 0) + 1
            summary = ", ".join(f"{v}× {k}" for k, v in sorted(types.items()))
            _success(f"Datasources: {len(ds_list)} found ({summary})")
            return True
        else:
            _fail(f"Datasources: HTTP {resp.status_code}")
            return False
    except Exception as e:
        _fail(f"Datasources: {e}")
        return False


def _check_llm() -> bool:
    try:
        from dashforge.config import settings

        provider = settings.llm_provider
        api_key = settings.llm_api_key
        model = settings.llm_model

        if not api_key and provider not in ("ollama", "bedrock"):
            _warn(f"LLM: no API key for {provider}")
            return False

        # Light validation — don't actually call the API
        if provider == "anthropic" and api_key.startswith("sk-ant-"):
            _success(f"LLM: {provider} / {model} (key looks valid)")
            return True
        elif provider in ("openai", "azure") and api_key.startswith("sk-"):
            _success(f"LLM: {provider} / {model} (key looks valid)")
            return True
        elif provider == "bedrock":
            try:
                import boto3

                session_kwargs: dict = {"region_name": settings.llm_bedrock_region}
                if settings.llm_aws_access_key_id:
                    session_kwargs["aws_access_key_id"] = settings.llm_aws_access_key_id
                    session_kwargs["aws_secret_access_key"] = settings.llm_aws_secret_access_key
                session = boto3.Session(**session_kwargs)
                # Mirror _build_boto3_session: assume role if configured
                if settings.llm_bedrock_role_arn:
                    sts = session.client("sts")
                    assumed = sts.assume_role(
                        RoleArn=settings.llm_bedrock_role_arn,
                        RoleSessionName="dashforge-bedrock",
                        DurationSeconds=3600,
                    )
                    creds = assumed["Credentials"]
                    session = boto3.Session(
                        aws_access_key_id=creds["AccessKeyId"],
                        aws_secret_access_key=creds["SecretAccessKey"],
                        aws_session_token=creds["SessionToken"],
                        region_name=settings.llm_bedrock_region,
                    )
                sts = session.client("sts")
                identity = sts.get_caller_identity()
                account = identity.get("Account", "?")
                model_id = settings.llm_bedrock_model_id or model
                _success(f"LLM: bedrock / {model_id} (AWS account {account}, region {settings.llm_bedrock_region})")
                return True
            except ImportError:
                _fail("LLM: bedrock requires boto3 — pip install 'dashforge[bedrock]'")
                return False
            except Exception as be:
                _fail(f"LLM: bedrock AWS auth failed — {be}")
                return False
        elif provider == "ollama":
            import httpx

            base = settings.llm_api_base or "http://localhost:11434"
            try:
                resp = httpx.get(f"{base}/api/tags", timeout=5)
                if resp.status_code == 200:
                    _success(f"LLM: ollama at {base} / {model}")
                    return True
            except Exception:
                pass
            _warn(f"LLM: ollama at {base} not reachable")
            return False
        else:
            _success(f"LLM: {provider} / {model} (key present)")
            return True
    except Exception as e:
        _fail(f"LLM: {e}")
        return False


def _check_archetypes() -> bool:
    try:
        from dashforge.archetypes.templates import ALL_ARCHETYPES

        total_panels = sum(len(a.panels) for a in ALL_ARCHETYPES)
        _success(f"Archetypes: {len(ALL_ARCHETYPES)} loaded, {total_panels} panels")
        return True
    except Exception as e:
        _fail(f"Archetypes: {e}")
        return False


def _check_signalfx() -> bool:
    try:
        import httpx

        from dashforge.config import settings

        realm = settings.signalfx_realm
        token = settings.signalfx_api_token
        if not token:
            _warn("SignalFx: no API token configured")
            return False

        resp = httpx.get(
            f"https://api.{realm}.signalfx.com/v2/metric",
            headers={"X-SF-TOKEN": token},
            params={"query": "*", "limit": 1},
            timeout=10,
        )
        if resp.status_code == 200:
            data = resp.json()
            count = data.get("count", "?")
            _success(f"SignalFx: connected to realm {realm} ({count} metrics)")
            return True
        elif resp.status_code == 401:
            _fail("SignalFx: authentication failed (HTTP 401) — check API token")
            return False
        else:
            _fail(f"SignalFx: HTTP {resp.status_code} from api.{realm}.signalfx.com")
            return False
    except Exception as e:
        _fail(f"SignalFx: {e}")
        return False


# ── dashforge connect grafana ────────────────────────────────────────────────
@cli.group()
def connect():
    """Connect to external services."""
    pass


@connect.command("grafana")
@click.option("--url", default=None, help="Grafana URL")
@click.option("--api-key", default=None, help="Grafana service account token")
def connect_grafana(url: str | None, api_key: str | None):
    """Test and persist Grafana connection."""
    _header("Connect to Grafana")
    _load_env()

    if url is None:
        url = _prompt("Grafana URL", "http://localhost:3000")
    if api_key is None:
        api_key = _prompt("API key (service account token)", "")

    if not api_key:
        _fail("API key is required")
        return

    # Test connection
    import httpx

    try:
        headers = {"Authorization": f"Bearer {api_key}"}
        resp = httpx.get(f"{url.rstrip('/')}/api/org", headers=headers, timeout=10)
        if resp.status_code != 200:
            _fail(f"Connection failed: HTTP {resp.status_code}")
            return
        org = resp.json()
        _success(f"Connected to \"{org.get('name', 'unknown')}\" at {url}")
    except Exception as e:
        _fail(f"Connection failed: {e}")
        return

    # Discover datasources
    try:
        resp = httpx.get(f"{url.rstrip('/')}/api/datasources", headers=headers, timeout=10)
        if resp.status_code == 200:
            ds_list = resp.json()
            _success(f"Found {len(ds_list)} datasources:")
            for ds in ds_list:
                _info(f"  {ds['name']} ({ds['type']})")
    except Exception:
        pass

    # Persist
    if _confirm("Save this connection?", default=True):
        _ensure_config()
        _update_config({"grafana": {"url": url}})
        _update_env({"GRAFANA_API_KEY": api_key})
        _success("Connection saved!")
        _info("Run `dashforge doctor` to verify full setup")


@connect.command("signalfx")
@click.option("--token", default=None, help="SignalFx API access token")
@click.option("--realm", default=None, help="SignalFx realm (us0, us1, us2, eu0, jp0, au0)")
def connect_signalfx(token: str | None, realm: str | None):
    """Test and persist Splunk SignalFx connection."""
    _header("Connect to Splunk SignalFx")
    _load_env()

    if realm is None:
        realm = _prompt("Realm (us0, us1, us2, eu0, jp0, au0)", "us1")
    if token is None:
        token = _prompt("API access token", "")

    if not token:
        _fail("API token is required")
        return

    # Test connection
    import httpx

    try:
        resp = httpx.get(
            f"https://api.{realm}.signalfx.com/v2/metric",
            headers={"X-SF-TOKEN": token},
            params={"query": "*", "limit": 1},
            timeout=10,
        )
        if resp.status_code == 401:
            _fail("Authentication failed — check your API token")
            return
        if resp.status_code != 200:
            _fail(f"Connection failed: HTTP {resp.status_code}")
            return
        data = resp.json()
        count = data.get("count", "?")
        _success(f"Connected to realm {realm} ({count} metrics available)")
    except Exception as e:
        _fail(f"Connection failed: {e}")
        return

    group_name = _prompt("Dashboard group name", "DashForge")

    # Persist
    if _confirm("Save this connection?", default=True):
        _ensure_config()
        _update_config({"signalfx": {"enabled": True, "realm": realm, "dashboard_group": group_name}})
        _update_env({"SIGNALFX_API_TOKEN": token})
        _success("Connection saved!")
        _info("Run `dashforge doctor` to verify full setup")


def _ensure_config():
    DASHFORGE_HOME.mkdir(parents=True, exist_ok=True)
    if not CONFIG_FILE.exists():
        CONFIG_FILE.write_text("# DashForge configuration\n")


def _update_config(updates: dict):
    """Merge updates into the YAML config file."""
    existing: dict = {}
    if CONFIG_FILE.exists():
        with open(CONFIG_FILE) as f:
            existing = yaml.safe_load(f) or {}

    def _deep_merge(base: dict, override: dict) -> dict:
        for k, v in override.items():
            if isinstance(v, dict) and isinstance(base.get(k), dict):
                base[k] = _deep_merge(base[k], v)
            else:
                base[k] = v
        return base

    merged = _deep_merge(existing, updates)
    with open(CONFIG_FILE, "w") as f:
        yaml.dump(merged, f, default_flow_style=False, sort_keys=False)


def _update_env(updates: dict):
    """Merge key=value pairs into ~/.dashforge/.env."""
    env_path = DASHFORGE_HOME / ".env"
    existing: dict = {}
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                existing[k.strip()] = v.strip()
    existing.update(updates)
    with open(env_path, "w") as f:
        f.write("# DashForge secrets\n")
        for k, v in existing.items():
            f.write(f"{k}={v}\n")
    env_path.chmod(0o600)


# ── dashforge test ───────────────────────────────────────────────────────────
@cli.command("test")
@click.option("--prompt", "-p", default=None, help="Custom test prompt")
@click.option("--open-browser/--no-open-browser", default=True, help="Open dashboard in browser")
def test_run(prompt: str | None, open_browser: bool):
    """Run a sample investigation and open the resulting dashboard."""
    _header("DashForge Test Run")
    _load_env()

    if prompt is None:
        prompt = "High latency on the checkout service in the last hour"
    _info(f'Prompt: "{prompt}"')
    console.print()

    import asyncio

    async def _run():
        from dashforge.models.schemas import DashRequest
        from dashforge.pipeline import run_pipeline

        req = DashRequest(prompt=prompt)
        _info("Running pipeline...")
        result = await run_pipeline(req)
        return result

    try:
        result = asyncio.run(_run())

        if result.dashboard_url:
            _success(f"Dashboard created: {result.dashboard_url}")
            _info(f"  UID: {result.dashboard_uid}")
            _info(f"  Panels: {result.panel_count}")
            _info(f"  Path: {result.path_used}")
            if result.archetypes:
                arch_str = ", ".join(f"{a.type} ({a.confidence:.0%})" for a in result.archetypes)
                _info(f"  Archetypes: {arch_str}")

            if open_browser and result.dashboard_url:
                _info("Opening in browser...")
                webbrowser.open(result.dashboard_url)
        else:
            _fail("Pipeline completed but no dashboard URL returned")
            if result.error:
                _fail(f"Error: {result.error}")

    except Exception as e:
        _fail(f"Pipeline error: {e}")
        _info("Run `dashforge doctor` to check your setup")


# ── dashforge learn ──────────────────────────────────────────────────────────
@cli.group()
def learn():
    """Learn operational language from existing dashboards."""
    pass


@learn.command("dashboard")
@click.argument("dashboard_uid")
@click.option("--backend", default="", help="Backend name, e.g. grafana or signalfx")
@click.option("--auto-approve/--pending", default=False, help="Immediately activate eligible mappings")
def learn_dashboard(dashboard_uid: str, backend: str, auto_approve: bool):
    """Ingest a dashboard and show what DashForge learned."""
    _header("Learn Dashboard")
    _load_env()

    import asyncio

    async def _run():
        from dashforge.dashboard_ingest import ingest_dashboard

        return await ingest_dashboard(
            dashboard_uid=dashboard_uid,
            backend_name=backend,
            auto_approve=auto_approve,
        )

    try:
        result = asyncio.run(_run())
    except Exception as e:
        _fail(f"Dashboard ingestion failed: {e}")
        _info("Run `dashforge doctor` to check backend connectivity.")
        return

    quality = result.get("signal_quality", {})
    impact = result.get("learning_impact", {})
    _success(f"Ingested {result.get('dashboard_title') or dashboard_uid}")
    _info(f"Status: {result.get('status', 'pending')}")
    _info(f"Panels: {result.get('panel_count', 0)}")
    _info(f"Metrics found: {len(result.get('metrics_found', []))}")
    _info(f"Signals inferred: {len(result.get('signals_inferred', []))}")
    _info(
        "Learning impact: "
        f"{impact.get('active_mappings_before_learning', 0)} active before, "
        f"{impact.get('candidate_mappings_pending_approval', 0)} candidate pending approval, "
        f"{impact.get('new_active_mappings_after_approval', 0)} newly active"
    )
    if quality:
        _info(
            "Inference quality: "
            f"{quality.get('taxonomy_matches', 0)} taxonomy, "
            f"{quality.get('heuristic_candidates', 0)} heuristic, "
            f"{quality.get('held_for_review', 0)} held for review"
        )
    explanations = quality.get("explanations", [])[:8]
    if explanations:
        _info("Top inferred mappings:")
        for item in explanations:
            confidence = round(item.get("confidence", 0.0) * 100)
            review = item.get("review_state", "")
            _info(
                f"  {item.get('signal_type', 'unknown')} <- {item.get('metric', '')} "
                f"({confidence}%, {item.get('source', '')}, {review})"
            )
            if item.get("reason"):
                _info(f"    {item['reason']}")
    if auto_approve:
        _info(f"Mappings created: {result.get('mappings_created', 0)}")


def _print_bulk_learning_summary(result: dict):
    _success(f"Learned from {result.get('dashboards_learned', 0)} {result.get('backend')} dashboards")
    _info(f"Dashboards discovered: {result.get('dashboards_discovered', 0)}")
    _info(f"Dashboards failed: {result.get('dashboards_failed', 0)}")
    _info(f"Metrics found: {result.get('metrics_found', 0)}")
    _info(f"Signals inferred: {result.get('signals_inferred', 0)}")
    _info(f"Indexed context rows: {result.get('indexed_context_rows', 0)}")
    if result.get("auto_approve"):
        _info(f"Mappings created: {result.get('mappings_created', 0)}")

    learned = result.get("learned", [])
    if learned:
        _info("Top learned dashboards:")
        for item in learned[:10]:
            _info(
                f"  • {item.get('dashboard_title') or item.get('dashboard_uid')} "
                f"({item.get('metrics_found', 0)} metrics, "
                f"{item.get('signals_inferred', 0)} signals, "
                f"{item.get('indexed_context_rows', 0)} indexed rows)"
            )

    failures = result.get("failures", [])
    if failures:
        _info("Failures:")
        for item in failures[:5]:
            _fail(f"  {item.get('dashboard_uid')}: {item.get('error')}")


def _run_backend_learning(backend_name: str, auto_approve: bool, limit: int):
    _header(f"Learn {backend_name.title()} Dashboards")
    _load_env()

    import asyncio

    async def _run():
        from dashforge.dashboard_ingest import learn_backend_dashboards

        return await learn_backend_dashboards(
            backend_name,
            auto_approve=auto_approve,
            limit=limit,
        )

    try:
        result = asyncio.run(_run())
    except Exception as e:
        _fail(f"Bulk learning failed: {e}")
        _info("Run `dashforge doctor` to check backend connectivity.")
        return

    _print_bulk_learning_summary(result)


@learn.command("grafana")
@click.option("--auto-approve/--pending", default=False, help="Immediately activate eligible mappings")
@click.option("--limit", default=500, show_default=True, help="Maximum dashboards to crawl")
def learn_grafana(auto_approve: bool, limit: int):
    """Crawl Grafana dashboards and persist learned operational context."""
    _run_backend_learning("grafana", auto_approve, limit)


@learn.command("signalfx")
@click.option("--auto-approve/--pending", default=False, help="Immediately activate eligible mappings")
@click.option("--limit", default=500, show_default=True, help="Maximum dashboards to crawl")
def learn_signalfx(auto_approve: bool, limit: int):
    """Crawl SignalFx dashboards and persist learned operational context."""
    _run_backend_learning("signalfx", auto_approve, limit)


@learn.command("approve")
@click.argument("dashboard_uid")
@click.option("--backend", default="", help="Backend name, e.g. grafana_json or signalfx")
def learn_approve(dashboard_uid: str, backend: str):
    """Approve a pending learned dashboard and activate mappings."""
    _header("Approve Learned Dashboard")
    _load_env()

    from dashforge.dashboard_ingest import approve_ingested_dashboard_record

    try:
        result = approve_ingested_dashboard_record(
            dashboard_uid=dashboard_uid,
            backend_name=backend or None,
        )
    except LookupError:
        _fail("Ingested dashboard not found")
        return

    if result.get("status") == "approved":
        _success(result.get("message", "Dashboard approved"))
        _info(f"Mappings created: {result.get('mappings_created', 0)}")
        _info(f"Archetype registered: {result.get('archetype_registered', False)}")
    else:
        _info(result.get("message", f"Dashboard already {result.get('status')}"))


@learn.command("reject")
@click.argument("dashboard_uid")
@click.option("--backend", default="", help="Backend name, e.g. grafana_json or signalfx")
def learn_reject(dashboard_uid: str, backend: str):
    """Reject a pending learned dashboard and remove it from default retrieval."""
    _header("Reject Learned Dashboard")
    _load_env()

    from dashforge.dashboard_ingest import reject_ingested_dashboard_record

    try:
        result = reject_ingested_dashboard_record(
            dashboard_uid=dashboard_uid,
            backend_name=backend or None,
        )
    except LookupError:
        _fail("Ingested dashboard not found or not pending")
        return
    except RuntimeError:
        _fail("Dashboard is no longer pending")
        return

    if result.get("status") == "rejected":
        _success(result.get("message", "Dashboard rejected"))
        _info(f"Rejected candidates recorded: {result.get('rejected_candidates', 0)}")
    else:
        _info(result.get("message", f"Dashboard already {result.get('status')}"))


@learn.command("ignore")
@click.argument("dashboard_uid")
@click.option("--backend", default="", help="Backend name, e.g. grafana_json or signalfx")
def learn_ignore(dashboard_uid: str, backend: str):
    """Ignore a pending learned dashboard without negative training data."""
    _header("Ignore Learned Dashboard")
    _load_env()

    from dashforge.signals import get_signal_store

    store = get_signal_store()
    if store.ignore_ingested_dashboard(dashboard_uid, backend_name=backend or None):
        _success("Dashboard ignored")
    else:
        _fail("Ingested dashboard not found or not pending")


@learn.command("search")
@click.argument("query")
@click.option("--service", default="", help="Optional service/component filter")
@click.option("--approved-only", is_flag=True, help="Only show approved/trusted context")
@click.option("--limit", default=10, show_default=True, help="Maximum context rows")
def learn_search(query: str, service: str, approved_only: bool, limit: int):
    """Search learned dashboards, panels, metrics, and signal mappings."""
    _header("Search Learned Context")
    _load_env()

    from dashforge.signals import LearningIndexUnavailable, get_signal_store

    store = get_signal_store()
    try:
        rows = store.search_learning_context(
            query,
            service=service,
            include_candidates=not approved_only,
            limit=limit,
        )
    except LearningIndexUnavailable as e:
        _fail(str(e))
        return
    if not rows:
        _info("No learned context matched.")
        return

    for row in rows:
        state = row.get("review_state", "candidate")
        _info(
            f"• {row.get('metric_name', '')} → {row.get('signal_type', '') or 'unclassified'} "
            f"({state}, {row.get('dashboard_title', '')} / {row.get('panel_title', '')})"
        )
        if row.get("reason"):
            _info(f"  {row['reason']}")


@learn.command("service")
@click.argument("service")
@click.option("--approved-only", is_flag=True, help="Only use approved/trusted context")
@click.option("--limit", default=50, show_default=True, help="Maximum context rows")
def learn_service(service: str, approved_only: bool, limit: int):
    """Describe a service from learned operational context."""
    _header(f"Service Context: {service}")
    _load_env()

    from dashforge.signals import LearningIndexUnavailable, get_signal_store

    try:
        summary = get_signal_store().describe_service(
            service,
            include_candidates=not approved_only,
            limit=limit,
        )
    except LearningIndexUnavailable as e:
        _fail(str(e))
        return
    _info(f"Matched context rows: {summary.get('matched_context_rows', 0)}")
    _info(f"Trusted rows: {summary.get('trusted_context_rows', 0)}")
    _info(f"Candidate rows: {summary.get('candidate_context_rows', 0)}")

    dashboards = summary.get("dashboards", [])
    if dashboards:
        _info("Dashboards:")
        for dashboard in dashboards[:8]:
            _info(
                f"  • {dashboard.get('dashboard_title') or dashboard.get('dashboard_uid')} "
                f"({dashboard.get('backend_name')}, {dashboard.get('review_state')})"
            )

    metrics = summary.get("top_metrics", [])
    if metrics:
        _info("Metrics:")
        for metric in metrics[:10]:
            signals = ", ".join(metric.get("signal_types", [])) or "unclassified"
            states = ", ".join(metric.get("review_states", []))
            _info(f"  • {metric.get('metric')} → {signals} ({states})")

    signals = summary.get("signals", {})
    if signals:
        _info("Signals:")
        for signal, count in list(signals.items())[:10]:
            _info(f"  • {signal}: {count}")


# ── dashforge serve ──────────────────────────────────────────────────────────
@cli.command()
@click.option("--host", default="0.0.0.0", help="Bind host")
@click.option("--port", "-p", default=8000, type=int, help="Bind port")
@click.option("--reload", is_flag=True, help="Enable auto-reload (dev mode)")
@click.option("--no-slack", is_flag=True, help="Disable Slack integration")
def serve(host: str, port: int, reload: bool, no_slack: bool):
    """Start the DashForge API server."""
    _load_env()

    if no_slack:
        os.environ["SLACK_BOT_TOKEN"] = ""
        os.environ["SLACK_APP_TOKEN"] = ""

    _header(f"DashForge Server — {host}:{port}")

    import uvicorn

    from dashforge.config import settings
    from dashforge.logging import configure_logging

    configure_logging(settings.log_level)

    _info(f"LLM: {settings.llm_provider} / {settings.llm_model}")
    _info(f"Grafana: {settings.grafana_url}")
    _info(f"Log level: {settings.log_level}")
    if settings.slack_bot_token:
        _info("Slack: enabled")
    else:
        _info("Slack: disabled")
    if settings.signalfx_enabled:
        _info(f"SignalFx: enabled (realm={settings.signalfx_realm})")
    else:
        _info("SignalFx: disabled")
    console.print()

    uvicorn.run(
        "dashforge.main:app",
        host=host,
        port=port,
        reload=reload,
        log_level=settings.log_level.lower(),
    )


# ── dashforge history ─────────────────────────────────────────────────────
@cli.group()
def history():
    """View investigation history and pipeline telemetry."""
    pass


@history.command("list")
@click.option("--limit", "-n", default=20, type=int, help="Number of records")
@click.option("--status", type=click.Choice(["success", "failed", "timeout"]), default=None)
@click.option("--user", default=None, help="Filter by user ID")
def history_list(limit: int, status: str | None, user: str | None):
    """List recent investigations."""
    _load_env()
    from dashforge.history import get_investigation_store

    store = get_investigation_store()
    investigations = store.list_recent(limit=limit, status=status, user_id=user)

    if not investigations:
        _info("No investigations found.")
        return

    if Table is not None:
        table = Table(title=f"Recent Investigations ({len(investigations)})")
        table.add_column("ID", style="dim", width=16)
        table.add_column("Status", width=8)
        table.add_column("Prompt", max_width=40)
        table.add_column("Path", width=10)
        table.add_column("Panels", justify="right", width=6)
        table.add_column("Time", justify="right", width=7)
        table.add_column("Archetypes", max_width=30)

        for inv in investigations:
            status_style = {
                "success": "[green]success[/]",
                "failed": "[red]failed[/]",
                "timeout": "[yellow]timeout[/]",
            }.get(inv["status"], inv["status"])

            archetypes = inv.get("archetypes", [])
            arch_str = ", ".join(f"{a['type']}({a['confidence']:.0%})" for a in archetypes[:2]) if archetypes else "—"

            table.add_row(
                inv["id"],
                status_style,
                (inv["prompt"][:37] + "...") if len(inv["prompt"]) > 40 else inv["prompt"],
                inv.get("path_used", "—"),
                str(inv.get("panel_count", 0)),
                f"{inv.get('total_time', 0):.1f}s",
                arch_str,
            )
        console.print(table)
    else:
        for inv in investigations:
            click.echo(f"  {inv['id']}  {inv['status']:8s}  {inv['prompt'][:50]}")


@history.command("show")
@click.argument("investigation_id")
def history_show(investigation_id: str):
    """Show full details of a single investigation."""
    _load_env()
    from dashforge.history import get_investigation_store

    store = get_investigation_store()
    inv = store.get(investigation_id)

    if inv is None:
        _fail(f"Investigation {investigation_id} not found")
        return

    _header(f"Investigation {inv['id']}")

    # Status
    status = inv["status"]
    if status == "success":
        _success(f"Status: {status}")
    elif status == "failed":
        _fail(f"Status: {status} — {inv.get('error', '')}")
    else:
        _warn(f"Status: {status}")

    console.print()
    _info(f"Prompt: {inv['prompt']}")
    _info(f"User: {inv.get('user_id', '—')}")
    _info(f"Time: {inv.get('total_time', 0):.2f}s")

    # Intent
    console.print()
    _header("Intent")
    _info(f"Summary: {inv.get('intent_summary', '—')}")
    _info(f"Domain: {inv.get('intent_domain', '—')}")
    _info(f"Services: {inv.get('intent_services', [])}")
    _info(f"Keywords: {inv.get('intent_keywords', [])}")
    _info(f"Problem type: {inv.get('problem_type', '—')}")
    archetypes = inv.get("archetypes", [])
    if archetypes:
        arch_str = ", ".join(f"{a['type']} ({a['confidence']:.0%})" for a in archetypes)
        _info(f"Archetypes: {arch_str}")

    # Discovery
    console.print()
    _header("Discovery")
    _info(f"Datasources: {inv.get('datasources_found', 0)} ({inv.get('datasource_types', [])})")
    _info(f"Metric catalog: {inv.get('metrics_catalog_size', 0)} metrics")
    _info(f"After ranking: {inv.get('metrics_ranked_size', 0)} metrics")
    _info(f"Selected: {inv.get('metrics_selected', [])}")

    # Queries
    console.print()
    _header("Queries")
    _info(f"Path: {inv.get('path_used', '—')}")
    _info(f"Panels: {inv.get('panel_count', 0)}")
    queries = inv.get("generated_queries", [])
    for q in queries[:10]:
        _info(f"  [{q.get('panel_title', '?')}] {q.get('expr', '')[:80]}")
    if len(queries) > 10:
        _info(f"  ... and {len(queries) - 10} more")

    # Validation
    warnings = inv.get("validation_warnings", [])
    if warnings:
        console.print()
        _header("Validation")
        _info(f"Panels dropped: {inv.get('panels_dropped', 0)}")
        for w in warnings[:5]:
            _warn(w)

    # Timings
    timings = inv.get("timings", {})
    if timings:
        console.print()
        _header("Timings")
        for step, secs in timings.items():
            _info(f"  {step}: {secs:.2f}s")

    # Result
    if inv.get("dashboard_url"):
        console.print()
        _success(f"Dashboard: {inv['dashboard_url']}")


@history.command("stats")
def history_stats():
    """Show aggregate investigation statistics."""
    _load_env()
    from dashforge.history import get_investigation_store

    store = get_investigation_store()
    s = store.stats()

    _header("Investigation Stats")
    total = s.get("total", 0)
    if total == 0:
        _info("No investigations recorded yet.")
        return

    _info(f"Total: {total}")
    _success(f"Succeeded: {s.get('succeeded', 0)}")
    _fail(f"Failed: {s.get('failed', 0)}")
    _warn(f"Timed out: {s.get('timed_out', 0)}")
    console.print()
    _info(f"Avg time: {s.get('avg_time', 0):.2f}s")
    _info(f"Avg panels: {s.get('avg_panels', 0):.1f}")
    _info(f"Avg catalog size: {s.get('avg_catalog_size', 0):.0f} metrics")
    console.print()
    _info(f"Archetype path: {s.get('archetype_path', 0)}")
    _info(f"Freeform path: {s.get('freeform_path', 0)}")


# ── Entry point ──────────────────────────────────────────────────────────────
def main():
    cli()


if __name__ == "__main__":
    main()
