"""Adapter for Prometheus-compatible datasources (Prometheus, Mimir, Cortex, Thanos)."""

from __future__ import annotations

import asyncio
from urllib.parse import quote

import structlog

from tacit.cache import make_cache_key, metric_cache
from tacit.config import settings
from tacit.grafana.adapters.base import DatasourceAdapter
from tacit.grafana.client import GrafanaClient
from tacit.models.schemas import DatasourceInfo, MetricEntry

logger = structlog.get_logger()

# Internal labels to exclude from dimension lists
_INTERNAL_LABELS = {"__name__", "instance", "job"}
_MAX_SAMPLE_METRICS = 50  # max metrics to fetch series samples for
_MAX_VALUES_PER_LABEL = 10  # max unique values shown per label
# Suffixes auto-generated by prometheus_client that are never useful for dashboards
_NOISE_SUFFIXES = ("_created", "_info")
_MAX_CATALOG_SIZE = 300  # hard cap sent to the LLM


class PrometheusAdapter(DatasourceAdapter):

    @property
    def query_language(self) -> str:
        return "promql"

    @property
    def supported_types(self) -> set[str]:
        return {"prometheus", "mimir", "cortex", "thanos"}

    async def _fetch_metric_labels(
        self,
        client: GrafanaClient,
        datasource: DatasourceInfo,
        metric_name: str,
    ) -> list[str]:
        """Fetch actual label names and sample values for a single metric via /api/v1/series."""
        try:
            data = await client.datasource_proxy_get(
                datasource.uid,
                f"api/v1/series?match[]={quote(metric_name)}",
            )
            series_list = data.get("data", []) if isinstance(data, dict) else []
            if not series_list:
                return []

            # Collect unique values per label across all returned series
            label_values: dict[str, set[str]] = {}
            for series in series_list[:20]:  # cap series to avoid huge payloads
                for k, v in series.items():
                    if k in _INTERNAL_LABELS:
                        continue
                    label_values.setdefault(k, set()).add(v)

            # Format as "label={val1,val2,...}"
            dims = []
            for label, values in sorted(label_values.items()):
                sample = sorted(values)[:_MAX_VALUES_PER_LABEL]
                dims.append(f"{label}={{{','.join(sample)}}}")
            return dims
        except Exception:
            logger.debug("prometheus_series_fetch_failed", metric=metric_name)
            return []

    async def _get_cached_catalog(
        self,
        client: GrafanaClient,
        datasource: DatasourceInfo,
    ) -> dict[str, list[str]]:
        """Return {metric_name: [dim_strings]} from cache or live fetch."""
        cache_key = make_cache_key("prom_catalog", datasource.uid)
        cached = metric_cache.get(cache_key)
        if cached is not None:
            logger.info("prometheus_catalog_cache_hit", datasource=datasource.name, metrics=len(cached))
            return cached

        # Fetch metric names
        try:
            data = await client.datasource_proxy_get(datasource.uid, "api/v1/label/__name__/values")
            if isinstance(data, dict):
                all_names: list[str] = data.get("data", [])
            elif isinstance(data, list):
                all_names = data
            else:
                all_names = []
        except Exception:
            logger.warning("prometheus_metric_list_failed", datasource=datasource.name)
            return {}

        # Drop auto-generated noise metrics
        all_names = [n for n in all_names if not n.endswith(_NOISE_SUFFIXES)]

        # Fetch per-metric labels with bounded concurrency to avoid
        # overwhelming the Grafana proxy / Prometheus instance.
        to_sample = all_names[:_MAX_SAMPLE_METRICS]
        sem = asyncio.Semaphore(settings.adapter_max_concurrent)
        fetch_errors = 0
        total_label_cardinality = 0

        async def _bounded_fetch(name: str) -> tuple[str, list[str]]:
            nonlocal fetch_errors, total_label_cardinality
            async with sem:
                try:
                    dims = await self._fetch_metric_labels(client, datasource, name)
                    total_label_cardinality += len(dims)
                    return name, dims
                except Exception:
                    fetch_errors += 1
                    return name, []

        tasks = [_bounded_fetch(name) for name in to_sample]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        catalog: dict[str, list[str]] = {}
        for name in all_names:
            catalog[name] = []  # default: no dims
        for result in results:
            if isinstance(result, tuple):
                catalog[result[0]] = result[1]

        metric_cache.set(cache_key, catalog)
        logger.info(
            "prometheus_catalog_cached",
            datasource=datasource.name,
            total=len(catalog),
            sampled_labels=sum(1 for v in catalog.values() if v),
            sample_count=len(to_sample),
            fetch_errors=fetch_errors,
            label_cardinality=total_label_cardinality,
        )
        return catalog

    async def _get_metric_metadata(
        self,
        client: GrafanaClient,
        datasource: DatasourceInfo,
    ) -> dict[str, tuple[str, str]]:
        """Return {base_metric_name: (unit, type)} from /api/v1/metadata.

        Prometheus metadata is keyed by the *base* metric name (without the
        histogram/summary suffixes ``_bucket``/``_sum``/``_count``), so callers
        should look up the base name. Cached alongside the catalog.
        """
        cache_key = make_cache_key("prom_metadata", datasource.uid)
        cached = metric_cache.get(cache_key)
        if cached is not None:
            return cached

        meta: dict[str, tuple[str, str]] = {}
        try:
            data = await client.datasource_proxy_get(datasource.uid, "api/v1/metadata")
            payload = data.get("data", {}) if isinstance(data, dict) else {}
            for name, entries in payload.items():
                if not entries:
                    continue
                first = entries[0] if isinstance(entries, list) else entries
                if isinstance(first, dict):
                    meta[name] = (first.get("unit", "") or "", first.get("type", "") or "")
        except Exception:
            logger.debug("prometheus_metadata_fetch_failed", datasource=datasource.name)

        metric_cache.set(cache_key, meta)
        return meta

    @staticmethod
    def _metadata_for(name: str, meta: dict[str, tuple[str, str]]) -> tuple[str, str]:
        """Look up metadata by metric name, falling back to the histogram base."""
        if name in meta:
            return meta[name]
        for suffix in ("_bucket", "_sum", "_count", "_total"):
            if name.endswith(suffix):
                base = name[: -len(suffix)]
                if base in meta:
                    return meta[base]
        return ("", "")

    async def discover_metrics(
        self,
        client: GrafanaClient,
        datasource: DatasourceInfo,
        keywords: list[str],
    ) -> list[MetricEntry]:
        catalog = await self._get_cached_catalog(client, datasource)
        if not catalog:
            return []

        all_names = list(catalog.keys())

        # Keyword pre-filter: prioritise keyword-matched metrics, then backfill
        kw_lower = [k.lower() for k in keywords]
        matched = [n for n in all_names if any(k in n.lower() for k in kw_lower)]
        unmatched = [n for n in all_names if n not in set(matched)]
        filtered = (matched + unmatched)[:_MAX_CATALOG_SIZE]

        metadata = await self._get_metric_metadata(client, datasource)

        logger.info(
            "prometheus_metrics_discovered",
            datasource=datasource.name,
            total=len(all_names),
            filtered=len(filtered),
            cache_size=metric_cache.size,
            metadata_entries=len(metadata),
        )

        entries: list[MetricEntry] = []
        for name in filtered:
            unit, metric_type = self._metadata_for(name, metadata)
            entries.append(
                MetricEntry(
                    name=name,
                    datasource_uid=datasource.uid,
                    datasource_name=datasource.name,
                    datasource_type=datasource.type,
                    query_language=self.query_language,
                    dimensions=catalog.get(name, []),
                    unit=unit,
                    metric_type=metric_type,
                )
            )
        return entries
